### ISSUE TITLE
Regression from 2.2 to 2.3:

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [webpro-nl/knip#109]
Continuing #108, bumping Knip to 2.3.0 in [template-typescript-node-package](https://github.com/JoshuaKGoldberg/template-typescript-node-package) gives:

```plaintext
Unused devDependencies (2)
eslint-plugin-eslint-comments  package.json
markdownlint-cli               package.json
Unlisted dependencies (3)
@typescript-eslint/eslint-plugin-recommended-requiring-type-checking  .eslintrc.cjs
@typescript-eslint/eslint-plugin-strict                               .eslintrc.cjs
eslint-comments                                                       .eslintrc.cjs
```

😞

**Comment by webpro** [comment]
Thanks for reporting this, that looks pretty awkward 🙈

I have a fix coming up, but it's merely passing unit tests. It's a strange undertaking to resolve package names from specifiers in eslint `extends` config. Do you maybe happen to know some truth to this? For example:

- `plugin:@typescript-eslint/recommended` → `@typescript-eslint/eslint-plugin`
- `plugin:@next/next/core-web-vitals` → `@next/eslint-plugin-next`

The way I see it, I have to basically strip off things like `/recommended`, but not (in this case) `/next`. I wasn't sure how to solve this properly, but at least there's some additional unit tests so most cases should be/stay OK.

I looked at https://github.com/eslint/eslintrc/blob/main/lib/shared/naming.js but it's only half the story.

I'm just venting here, no need to get into it if it's not interesting!

**Comment by webpro** [comment]
A fix is in [v2.3.1](https://github.com/webpro/knip/releases/tag/2.3.1).

**Comment by JoshuaKGoldberg** [comment]
Haha it very much is interesting - and a known thing a lot of us in ESLint space aren't overjoyed about. [ESLint's now "flat" config system](https://eslint.org/blog/2022/08/new-config-system-part-2) is much better in this context. It has folks `import` as they normally would.

```js
import customConfig from "eslint-config-custom";

export default [
    customConfig,
    {
        files: ["**/*.js", "**/*.cjs"],
        rules: {
            "semi": "error",
            "no-unused-vars": "error"
        }
    }
];
```

**Comment by webpro** [comment]
The new config system is simply already supported by Knip because of that.

**Comment by webpro** [comment]
Since I believe this issue is fixed I'm going to close this one. Let me know if you encounter any issues!
