### ISSUE TITLE
Re-export of class with decorator fails

### ISSUE THREAD

**Issue by fb55** [webpro-nl/knip#215]
When a class with a (legacy) decorator is re-exported, usage of the re-exported value will not be picked up.

Example:

**`entry.ts`:**

```ts
import { Subject } from "./level1.js";

console.log(`Hello ${Subject.subjectName}!`);
```

**`level1.ts`:**

```ts
export * from "./level2.js";
```

**`level2.ts`:**

```ts
function Decorator() {
  return function (...args: any[]) {
    // do something with the target class
  };
}

@Decorator()
export class Subject {
  static subjectName = "world";
}
```

**Expected:** Knip reports no errors.

**Result:**

```
Unused exports in namespaces (1)
Subject  level2.ts
```

Note that a direct import of `level2.js` succeeds; this error is limited to re-exports.

**Comment by webpro** [comment]
Thanks for the bug report, this might fix more edge cases.

**Comment by fb55** [comment]
Wow that was a quick turnaround. Thanks!
