### ISSUE TITLE
Support `working-directory` keyword in GitHub Actions workflows

### ISSUE THREAD

**Issue by auvred** [webpro-nl/knip#433]
Followup for https://github.com/webpro/knip/pull/432

I'm working on integrating knip into the [typescript-eslint](https://typescript-eslint.io) repo (https://github.com/typescript-eslint/typescript-eslint/pull/8192)

We have GH workflow step that [runs in the specified working-directory](https://github.com/typescript-eslint/typescript-eslint/blob/3d729303dd5cfd18ccb823e96f0e8761fda6adab/.github/workflows/ci.yml#L130). Unfortunatelly, knip doesn't understand this syntax right now and [reports](https://github.com/typescript-eslint/typescript-eslint/actions/runs/7424440544/job/20204186504?pr=8192#step:5:188) `stylelint` as unused binary
```plaintext
Unlisted binaries (1)
stylelint  .github/workflows/ci.yml
```

GitHub Docs: [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory)

I thought about sending a PR, but I couldn't find an example in the code of existing plugins on how to handle similar situtations (monorepo dependency is referenced by file from repository root)

**Comment by webpro** [comment]
This is a totally valid bug report, but currently a non-trivial thing to handle in Knip.

Even if we'd take the `working-directory` into account to accomodate for something to run in another directory (which doesn't have to be another workspace), we'd need to understand this is in another workspace and "transfer" the `stylelint` dependency from the root workspace to the appropriate workspace.

For now the only suggestions I can do:

- Move or copy (depending on usage) the `stylelint` to the root workspace `devDependencies`
- Add `stylelint` to `ignoreDependencies` for the root workspace.

I really value this feedback, as it enforces the idea that some generic improvements need to be made in the capabilities of core and plugins. But there are other areas I consider higher priority at the moment. Let's just keep this issue open for visbility.

**Comment by webpro** [comment]
Going to reject this one, since it does not match what Knip currently offers, and we don't have the bandwidth/resources to implement RFCs like this.

**Comment by webpro** [comment]
Doing some refactoring that unlocks features like this. In the next version, Knip will support `working-directory` and `path` in GA workflow steps. You could try an early version if you like:

```
npm install -D https://pkg.pr.new/knip@f1349c2
```

**Comment by auvred** [comment]
I can confirm that our original issue has been fixed in the latest version of Knip: https://github.com/typescript-eslint/typescript-eslint/commit/beba27af1a9c23bae6a738b04227bf607a1b37c6#diff-a55fd3ab189e220a273770f57af40594369d9d7eb30d621d4d83fc78fd439288L32-L35

Thanks!

**Comment by webpro** [comment]
Awesome. thanks for the heads up!
