### ISSUE TITLE
Respect up-the-tree `.gitignore` files

### ISSUE THREAD

**Issue by alecmev** [webpro-nl/knip#531]
I have a `.gitignore` in my `~` with the following contents:

```gitignore
.scratch/
```

This allows me to plop `.scratch` directories all over the place and put not-for-remote stuff there like personal notes, half-baked code snippets, etc. Knip, unfortunately, doesn't look at `~/.gitignore` and reports code files in `.scratch` directories as unused.

I don't want to add `.scratch` to the repo `.gitignore` because it has nothing to do with the project. I don't want to store these files outside of the repo because I want to keep them close to the packages they're related to.

**Comment by webpro** [comment]
Does something like npm do the same eg when publishing?

**Comment by alecmev** [comment]
To frame this a little bit differently, how else could I tell Knip to ignore `**/.scratch/**` without polluting the configuration?

**Comment by webpro** [comment]
I'm not against the feature per se, but I also don't want unexpected results. What might be a feature to you, could be a hard-to-track and tricky-to-overcome issue to someone else.

So if other tools use it as well it's common/expected behavior.

> To frame this a little bit differently, how else could I tell Knip to ignore `**/.scratch/**` without polluting the configuration?

You can use `ignore` at the root config with this pattern. If you don't fancy that you could perhaps use a `knip.ts` and make it more DRY.

**Comment by alecmev** [comment]
I'm struggling to find examples. Prettier doesn't respect `.gitignore`, nor does ESLint. Biome, however, [does](https://github.com/biomejs/biome/discussions/1016) (at least intends to). Outside of JavaScript, RipGrep [does too](https://github.com/BurntSushi/ripgrep/issues/611#issuecomment-331692791), and [fd](https://github.com/sharkdp/fd/issues/4). Can you maybe suggest some more projects to take a look at?

> I'm not against the feature per se, but I also don't want unexpected results. What might be a feature to you, could be a hard-to-track and tricky-to-overcome issue to someone else.

On the one hand, I agree, changes like this require justification. On the other hand, Git is the common denominator here. If a file ultimately isn't committed, does it make sense to ever take it into consideration?

**Comment by TheKnarf** [comment]
It should probably just follow whatever `git check-ignore` does?

**Comment by webpro** [comment]
Since I'm convinced this should be in Knip I've worked on this feature today. Would appreciate your feedback and verify if it works as expected. Performance should not be affected noticeably (you can use `--performance` before/after to verify).

You can install this preview using e.g.:

```
npm i -D https://pkg.pr.new/knip@359e624
```

It should respect `.gitgnore` files up-the-tree, also outside the current `.git` repo. You can use the `--debug` flag and look for "Parsed gitignore files" to see the files parsed and the resulting glob patterns to ignore.

cc @alecmev @TheKnarf @phiresky @drodil

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.30.0. See [Release 5.30.0](https://github.com/webpro-nl/knip/releases/tag/5.30.0) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._

**Comment by alecmev** [comment]
Works great, thank you! 👍

**Comment by davidsickmiller** [comment]
I just started using knip yesterday, and I spent a fair amount of time banging my head against the wall trying to figure out why it was unable to find any project files.  Eventually I worked out that my project's parent directory had a .gitignore file that was excluding virtually all the files.

Now that I know this quirky behavior, it's no longer a problem for me.  But for future users, I wonder if this feature is more likely to cause problems than provide benefits.

If you want to keep it in, it might be worth adding to the troubleshooting doc?

**Comment by alecmev** [comment]
Out of curiosity, can you elaborate a little on your setup, please? What code are you running Knip on that’s not in version control? Something generated?

**Comment by davidsickmiller** [comment]
> Out of curiosity, can you elaborate a little on your setup, please? What code are you running Knip on that’s not in version control? Something generated?

I'm running Knip on code that's in source control (git).

The setup is unusual, though, because I have a working copy inside another working copy:
```
 - workspace/ <-- working copy of a repo containing Vagrant and Puppet config files
    ./app1/ <-- working copy of an application
    ./app2/ <-- working copy of another application
```

There's a .gitignore file in `workspace` with this line: `*/` to ignore all the subdirectories.

Running knip inside app1 (or app2) causes all files to be ignored due to that.

**Comment by webpro** [comment]
Sorry to hear it was frustrating, David. To be honest, while it might be unexpected occasionally, it's how `.gitignore` files work.

- Knip respecting `.gitignore` is mentioned here: https://knip.dev/explanations/entry-files#ignored-files
- Debug mode reveals what `.gitignore` files are used, and the effective ignore patterns (https://knip.dev/guides/troubleshooting#debug)

> But for future users, I wonder if this feature is more likely to cause problems than provide benefits.

You could be right here, but from my perspective, I've seen more users complain before this behavior was implemented compared to after.

> If you want to keep it in, it might be worth adding to the troubleshooting doc?

I'm leaning towards keeping it in. We should do a better job regarding debugging and output, as that's pretty overwhelming and unclear perhaps, especially in larger project.

**Comment by davidsickmiller** [comment]
I appreciate the thoughtful reply. 

I think you may be overlooking a pertinent detail. Git does indeed read .gitignore files from parent directories, but it doesn't go beyond the top of the working copy. Knip does go beyond this. 

This SO page may be useful: https://stackoverflow.com/questions/47755938/git-ignoring-gitignore-file-in-parent-directory

**Comment by webpro** [comment]
Just tried it, and you're right. Although what is respected beyond the git repo is the global `.gitignore` file, so that's where my assumption came from back then.

Should've actually tried `git check-ignore`, it has clear behavior and Knip should follow it.

**Comment by webpro** [comment]
This has now been patched in v5.61.0. Knip still respects `.gitignore` files "up the tree", but stops walking up after finding a `.git` folder. Which typically means no such files are added, as Knip should be ran from root of repo.

Sorry everyone, this was sloppy on my end.

**Comment by alecmev** [comment]
My bad, I forgot that I actually had to change `core.excludesFile` for Git to consider `~/.gitignore`. So this is a welcome fix! But yeah, it unfixes the original issue 😄 What about this part of [gitignore spec](https://git-scm.com/docs/gitignore#_description)?

> - Patterns which a user wants Git to ignore in all situations (e.g., backup or temporary files generated by the user’s editor of choice) generally go into a file specified by `core.excludesFile` in the user’s `~/.gitconfig`. Its default value is $XDG_CONFIG_HOME/git/ignore. If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/ignore is used instead.
>
> ... Higher-level Git tools, such as **git status** and **git add**, use patterns from the sources specified above.

**Comment by webpro** [comment]
There's still the finding `.gitgnore` up-the-tree, but it ends at the Git root dir. Which indeed is usually the same behavior as before v5.30, but not always: e.g. root of the repo may be different from Knip scope, and Knip has `--directory` arg.

The part of the spec you mention (global gitignore) should probably be implemented too, but it's a different issue.

**Comment by alecmev** [comment]
> ... but it's a different issue.

As the author of this issue, I can say with confidence that it's the other way around 😁 (and I just described the root of the problem poorly) But I don't mind tracking it in a new one, done! https://github.com/webpro-nl/knip/issues/1136
