### ISSUE TITLE
Allow just the workspace "name" instead of full path when using --workspace

### ISSUE THREAD

**Issue by tomdee** [webpro-nl/knip#538]
The current behavior (from https://knip.dev/features/monorepos-and-workspaces)
```
Lint a single workspace
Use the --workspace (or -W) argument to focus on a single workspace (and let Knip run faster). Example:

Terminal window
knip --workspace packages/my-lib
```

The desired behavior:
```
knip --workspace my-lib
```
i.e. drop the `packages` prefix.

This matches how `npm` (and I think `yarn`) work
e.g. this works in npm, even if `my-lib` is stored in `packages`
```
npm run --workspace my-lib <script-name>`        
```

**Comment by webpro** [comment]
At first I wanted to implement this, but it's a bit laborious and also it would mean inconsistency in configuration option values (e.g. `ignoreWorkspaces` does not support this). So mainly for reasons of simplicity and consistency I'm going to close this one.
