### ISSUE TITLE
Allow marking a whole directory of exports as `@internal` via knip config file

### ISSUE THREAD

**Issue by camjackson** [webpro-nl/knip#553]
## Context

In short:

- My project contains dozens of test helper functions for things like constructing test data, and mocking dependencies
- When running knip in `--production` mode:
  - A test helper should be marked as dead code if it is not used anywhere at all
  - A test helper should **not** be marked as dead code if it is only called from test code

As discussed previously on discord ([link to original message](https://discord.com/channels/1143209786612125696/1143209787140620310/1208377171635081277), [link to subsequent thread](https://discord.com/channels/1143209786612125696/1143209787140620310/1208544370354036796)), the above requirements can be met by the [`@internal`](https://knip.dev/reference/jsdoc-tsdoc-tags#internal) tag. However, given that:

1. I'm not currently using JS/TSDoc; and
2. I have many of these helpers; and
3. They are all located in a single directory;

I would much prefer to mark the whole directory as being "internal" rather than tagging each export individually in the code.

## Proposal

Similar to how the knip config file allows me to ignore files, I would like to mark files/directories as internal via the config file. E.g.

```ts
// knip.ts

const knipConfig = {
  ignore: [
    'src/someExceptionalFile.ts',
  ],
  internal: [
    'src/testHelpers/',
  ],
};

export default knipConfig;
```

This would be equivalent to adding the `@internal` tag to everything that's exported from that module or directory.

**Comment by webpro** [comment]
Going to reject this one, since it does not really match what Knip currently offers, and we don't have the bandwidth/resources to implement RFCs like this.
