### ISSUE TITLE
add --project and --entry flags

### ISSUE THREAD

**Issue by jake-stewart** [webpro-nl/knip#573]
removes need for creating temporary knip.json

**Comment by webpro** [comment]
There are default values for those options, Knip looks in `package.json`, and plugins look in more configuration files. Do you think there something common missing, or is it just for convenience?

In general I'm not after parity between CLI arguments and configuration file options, especially considering monorepos are supported as well (making CLI args cumbersome).

**Comment by jake-stewart** [comment]
@webpro i would find the flags useful for scriptability. i could install knip globally and use a wrapper script with the args i prefer. i would be able to use it on any project without having to create a temporary knip.json just to define entry point.

also, i would be able to set different entry points interactively to view different graphs. (i sometimes have multiple entry points)

**Comment by webpro** [comment]
Going to close this issue. Once this would land, I feel like chances are the other configuration file options will be requested as CLI arguments as well. As said, in general I'm not after parity here.
