### ISSUE TITLE
Support local custom plugin

### ISSUE THREAD

**Issue by zhanzizhen** [webpro-nl/knip#641]
Is there no other more convenient way except for submitting the code to the Knip repository to create a new plugin (which may be very time-consuming)?
It would be convenient if knip could support local plugins like:
```ts
// knip.config.js
{
  "my-plugin": {
      title:xxx,
      enablers: xxx,
      isEnabled: xxx,
      config:xxx,
      resolveConfig: xxx
  },
}
```

**Comment by webpro** [comment]
Unfortunately, there is not. Sorry to hear building new plugins for Knip is time-consuming for you. Supporting this means it'll be more time-consuming for me, and I currently don't fancy this idea.

**Comment by FelipePhilippCbh** [comment]
An use case: I have a few private libraries which are used across my work and would be great to have a way to add a local plugin to it. Currently the workaround is to either ignore files or add a `@public` comment
