### ISSUE TITLE
Support import.meta.resolve (in Pino v7+ transports)

### ISSUE THREAD

**Issue by haines** [webpro-nl/knip#642]
Pino v7+ allows you to create a transport, which is a module that runs in a worker thread to consume logs ([docs](https://github.com/pinojs/pino/blob/main/docs/transports.md)).

Knip is currently giving a false positive for an unused file containing my transport.

Here is a minimal reproduction: https://stackblitz.com/edit/github-ggjbcu?file=src%2Findex.ts

```ts
import { pino } from 'pino';

const logger = pino({
  // ./transport.js, or in a TypeScript project ./transport.ts, should not be unused
  transport: { target: import.meta.resolve('./transport.js') },
});

logger.info('Hello, world!');
```

For this to work as expected, does Knip need to provide a Pino plugin?

**Comment by webpro** [comment]
Knip already adds entry files from `require.resolve()` specifiers. I think we just need to add the same for `import.meta.resolve`.

**Comment by webpro** [comment]
This is a core feature btw, no need for a plugin.
