### ISSUE TITLE
Unused functions are not being detected

### ISSUE THREAD

**Issue by btd1337** [webpro-nl/knip#643]
Unused functions are not being detected.

How to reproduce:

1. Create one file in any folder inside your project.
2. Create three functions inside this file

```ts
// file: src/test.ts

// unused
export function foo() {
  bar();
}

// used by foo
export function bar() {
  console.log('bar'); 
}

// used by other file
export function zoo() {
  console.log('zoo');  
}
```

3. import zoo function in other file

4. Test if Knip detect this unused function

```ts
pnpm knip --include exports,types,nsExports,nsTypes

> project@9.1.0 knip /home/helder/project
> knip "--include" "exports,types,nsExports,nsTypes"

✂️  Excellent, Knip found no issues.
```

Testing with another package that Knip indicates is similar: [ts-prune](https://github.com/nadeesha/ts-prune):

```
ts-prune | grep -v '(used in module)'

src/test.ts:1 - foo
```

Note that ts-prune detects the unused function, but Knip don't. Why doesn't Knip detect this?

**Comment by webpro** [comment]
By default, Knip does not report unused exports in entry files.

**Comment by btd1337** [comment]
@webpro thank you for responding, but that is not the case. This is not about the entry point file. The pattern occurs within other files that are not the entry point file.

**Comment by webpro** [comment]
The `src/test.ts` file can also be an entry file, depending on the enabled plugins. That's why I'd need a reproduction to properly look into it.

You can also use `--debug` to get more verbose output, maybe it clears things up.

**Comment by btd1337** [comment]
I gave a very simple example. Add any other file as an entrypoint besides this other file as an example that I mentioned above.

You should have as behavior, that the unused function will not be detected.

My case is that I have a very large project, in which Knip is not able to detect many unused functions, and ts-prune can.
I tried to demonstrate a basic example of how to reproduce, because I believe that Knip should be able to replace ts-prune.

**Comment by webpro** [comment]
Sorry, but without a reproduction there's nothing for me to look into. I hope you understand I can't copy-paste everyone's "how to reproduce" dumps.

There's reasons Knip works the way it does by default. There's various ways Knip can be configured to make it behave as you need. 

Maybe you're looking for flags like these:

- https://knip.dev/reference/configuration#includeentryexports
- https://knip.dev/reference/configuration#ignoreexportsusedinfile
