### ISSUE TITLE
"ignore" file working even though it shouldn't based on the docs

### ISSUE THREAD

**Issue by swingthrough** [webpro-nl/knip#650]
When I run `knip --include files` to list unused files in my project, there are a couple of files shown, one of which is `src/mockServiceWorker.js`.

So I created `knip.config.ts` with the following configuration:
```
import type { KnipConfig } from 'knip';

const config: KnipConfig = {
	ignore: ['src/mockServiceWorker.js'],
};

export default config;
```

If I run `knip --include files` with this config, it no longer reports `src/mockServiceWorker.js`.

However, [in the docs](https://knip.dev/guides/configuring-project-files#:~:text=This%20is%20not%20a%20good%20idea%2C%20since%20ignore%20patterns%20have%20only%20one%20goal%3A%20to%20exclude%20issues%20in%20matching%20files%20from%20the%20report.%20Files%20matching%20ignore%20patterns%20are%20not%20excluded%20from%20the%20analysis%2C%20only%20their%20issues%20are%20not%20reported.) there is a statement:

_This is not a good idea, since `ignore` patterns have only one goal: to exclude issues in matching files from the report. Files matching `ignore` patterns are not excluded from the analysis, only their issues are not reported._

Why does it work then?

Also what would be the correct way to exclude it?
I tried this:
```
import type { KnipConfig } from 'knip';

const config: KnipConfig = {
	project: [
		'**/*.{js,cjs,mjs,jsx,ts,cts,mts,tsx}',
		'!src/mockServiceWorker.js',
	],
};

export default config;
```

And it works. Is this the correct way?

**Comment by webpro** [comment]
Both are fine, the latter is recommended.

The docs don't contradict anything here?

**Comment by swingthrough** [comment]
Okay I think I get it now, it also states:

> This also hurts performance, since the files are first analyzed, and eventually filtered out.

I interpreted the part _"only their issues are not reported"_ as issues inside the file, but I guess it means the whole file being unused is also an issue of the file, and therefore filtered out (but only after the analysis ran on the file).

**Comment by webpro** [comment]
Indeed! Any issue with files that match the ignore pattern is not reported.
