### ISSUE TITLE
`ignore` is not applied for Auto-fix

### ISSUE THREAD

**Issue by taro-28** [webpro-nl/knip#653]
Hello!
I encountered a bug that `ignore` is not applied when using the Auto-fix.

# Reproduction
https://stackblitz.com/edit/knip-fix-example?file=knip.json
```sh
❯ npm run knip-fix

> knip-fix
> knip --fix

# Output is only for non-ignored files, but actually the ignored files are also fixed
Unused exports (2)
b  unknown  nonIgnored.js:2:14               (fixed)
b  unknown  packages/foo/nonIgnored.js:2:14  (fixed)
```

# Cause
The likely cause is that within `collector.addIssue`, even if the addition of an `issue` is ignored, `IssueFixer` still adds `fixes`.

# Suggested Fix
I think it would be better if `addIssue` returned `issue` when added, and only add to `fixer` when `issue` is returned here.
https://github.com/webpro-nl/knip/blob/693192b931680c2694d3e0aa992196d670a3a687/packages/knip/src/index.ts#L512-L523

```typescript
const issue = collector.addIssue({
  type,
  ...
});
if (issue) {
  if (isType) fixer.addUnusedTypeNode(filePath, exportedItem.fixes);
  else fixer.addUnusedExportNode(filePath, exportedItem.fixes);
}
```

Would it be alright if I proceed with this approach and create a pull request with the fix and additional tests?

**Comment by webpro** [comment]
Excellent! Thanks for catching this, and your idea/approach sounds great.
