### ISSUE TITLE
Not working with @emotion/styled during string interpolation

### ISSUE THREAD

**Issue by wbern** [webpro-nl/knip#655]
Repo with repro: https://github.com/wbern/repro-knip-emotion

Steps:
1. Run `pnpm install`
2. Run `pnpm knip`

Expected output:

```
// No unused things
```

Received output:
```
Unused exports (1)
slideIn  unknown  components/Dialog/Dialog.styles.tsx:4:14
```

Node version: `v18.19.0`
Package manager: `pnpm`

**Comment by webpro** [comment]
Closing this, works as expected.
