### ISSUE TITLE
Dependency reported as "unused" even if it's used with require.resolve(...)

### ISSUE THREAD

**Issue by OmniSliver** [webpro-nl/knip#657]
- What's the latest version it worked properly for you?
  - 5.16.0
- What's the first version it stopped working properly for you?
  - Pre release: 5.17.0-canary.0
  - Release: 5.17.0

E.g.:
```javascript
console.log(require.resolve('querystring-es3'))
```
results in
```
Unused devDependencies (1)
querystring-es3  package.json
```

When does this matter? `require.resolve` is used when specifying Webpack's [resolve.fallback](https://webpack.js.org/configuration/resolve/#resolvefallback).

This may be related to the fix used for #642

**Comment by webpro** [comment]
Can you please provide a reproduction? Tests and coverage shows it's still functional. Of course a regression could've been introduced, so I'd need to see how exactly.

The issue you link to hasn't been fixed yet.

**Comment by OmniSliver** [comment]
Repro here: https://github.com/OmniSliver/knipIssue567Repro

Thanks!

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.17.2. See [Release 5.17.2](https://github.com/webpro-nl/knip/releases/tag/5.17.2) for release notes._

_Using Knip in a commercial project? Please consider [sponsoring me](https://github.com/sponsors/webpro)._

**Comment by webpro** [comment]
Thanks @OmniSliver! Should be good now.

**Comment by OmniSliver** [comment]
All good now. Thanks for always being on top of the issues!
