### ISSUE TITLE
Links are broken all over the docs 

### ISSUE THREAD

**Issue by AgarkovRoman** [webpro-nl/knip#666]
Steps to reproduce:

- open https://knip.dev/features/monorepos-and-workspaces/
- click on "integrated monorepos" link

actual behavior - opens https://knip.dev/features/monorepos-and-workspaces/integrated-monorepos
expected behavior - opens https://knip.dev/features/integrated-monorepos

One of the possible solution - rewrite links in docs like this:
<img width="978" alt="Screenshot 2024-05-30 at 19 01 01" src="https://github.com/webpro-nl/knip/assets/47497850/829b07a1-3893-4a1f-bfcc-09d11ab15b98">

But not sure if this is the right way, maybe someone knows how Astro can handle this 🤔

**Comment by webpro** [comment]
Thanks for reporting this!

I just migrated from Vercel to Netlify, and I didn't realize the trailing slash. The links in the main navigation are fine, but within content.

I want the internal Markdown links to work as well. To hop around in the editor or in the GitHub Ui with Markdown previews.

Unfortunately I can't find how to set this in either Astro/Starlight or Netlify. So I've come up with a little one-liner to move all `path/index.html` to `path.html` files after building the site in Netlify.
