### ISSUE TITLE
Stricter check for `--workspace` paths

### ISSUE THREAD

**Issue by zheng** [webpro-nl/knip#667]
Knip checks that the workspace passed is a filepath, but if it isn't a javascript/typescript project, it continues with some NOT_FOUND project and silently passes

```2024-05-31T19:30:05.9794785Z [33m[*][39m Included workspaces
2024-05-31T19:30:05.9795029Z [
2024-05-31T19:30:05.9795315Z   [32m'obsidian'[39m,
2024-05-31T19:30:05.9795822Z   [32m'NOT_FOUND_home/runner/work/obsidian/obsidian/apps/test-rollout-management'[39m
2024-05-31T19:30:05.9796256Z ]
```

I think it should loudly complain instead. We love and rely on knip at Vanta. But after a recent refactor 2 weeks ago, our knip checks have not been running

**Comment by webpro** [comment]
> We love and rely on knip at Vanta.

If Knip is of value to the company, please consider becoming a sponsor: https://knip.dev/sponsors

**Comment by webpro** [comment]
Thanks for the report, @zheng.

> But after a recent refactor 2 weeks ago, our knip checks have not been running

Can you elaborate?
