### ISSUE TITLE
React Rouer V6 lazy api how to ignore 

### ISSUE THREAD

**Issue by faner11** [webpro-nl/knip#671]
doc: https://reactrouter.com/en/main/route/lazy#lazy

![image](https://github.com/webpro-nl/knip/assets/26560612/f3d21894-750d-4bfe-b6ec-30dd4947059c)
I did the same as in the documentation, exported the loader and Component in tsx. imported the file where it was used. 

But knip prompts me that I am not using them and how should I configure them.

<img width="624" alt="image" src="https://github.com/webpro-nl/knip/assets/26560612/e7ad96e3-6606-4e31-bbae-721c2f0e14b9">

**Comment by webpro** [comment]
Sorry, but screenshots are not an actual [minimal reproduction](https://knip.dev/guides/troubleshooting#minimal-reproduction).

Maybe you need this: https://knip.dev/guides/handling-issues#external-libraries (`--include-libs`)

**Comment by faner11** [comment]
I made a simple demo

https://codesandbox.io/p/devbox/m8cg2w?migrateFrom=yzxkdt

**Comment by webpro** [comment]
Yes that works as expected: 

```
Unused exports (2)
Component  unknown  a.ts:1:14
loader     unknown  a.ts:5:14
```

**Comment by webpro** [comment]
```ts
const a = await import("./a");
```

In this example, `a` is the default export of `a.ts` (which does not exist). Use named imports for named exports.

**Comment by faner11** [comment]
Haha, I understand, but I don't want knip to prompt Component/loader Unused exports, because it's similar to a convention that react router v6 and remix suggests.

**Comment by webpro** [comment]
So you want to ignore such files from the report? That's documented here: https://knip.dev/reference/configuration#ignore

Depending on the context, `--include-libs` might help (has reportedly helped others too in similar cases).

**Comment by faner11** [comment]
I can't use ignore because I can't enumerate every file, and I can't use regular matching because only page-level files need to ignore Component/loader, and other files don't need to be ignored. The effect I expect is to only ignore the two exports of Component/loader, and other exports in the file will still be checked.
`--include-libs` Not applicable to this scenario.

**Comment by webpro** [comment]
Related:

- https://github.com/webpro-nl/knip/issues/522
- https://github.com/webpro-nl/knip/issues/556

Another option is to use [JSDoc tags](https://knip.dev/reference/jsdoc-tsdoc-tags)

**Comment by faner11** [comment]
Ok, I understand, JSDoc tags will work, thank you @webpro  !

**Comment by webpro** [comment]
Yeah, this is what we have in store now. I guess Knip could/should add `ignoreExports` or something for cases like this (although I don't fancy folks turning to it too easily without analyzing what exports are in fact unused). Going to close this for now.
