### ISSUE TITLE
5.7.0: Failing to detect extensionless imports in some TS configurations.

### ISSUE THREAD

**Issue by Jym77** [webpro-nl/knip#672]
Switching from knip 5.6.1 to 5.7.0, extension-less imports in TS files seem to not be followed correctly (this depends quite heavily on the TS config too 😕)

[Minimal repro](https://codesandbox.io/p/sandbox/lingering-voice-zf62r6-cy686t)

With knip 5.6.1, `packages/shared/src/foo.ts` is not reported (it is imported in `index.ts` through `export * from "./foo"`). With knip 5.7.0 (and the few above I've tried, up to 5.17.4), it is (incorrectly) reported.

This has quite some unstability with what's in the `tsconfig.json`. Notably, with the default ones, there was no problem (and at least `"module": "commonjs"` is needed). I've copied my full (small) config in the minimal repro to trigger the problem.
(the `.d.ts` are also reported, but that's unrelated, I assume due to them not being `.gitignore`d or similar)

Adding the extension to the export with `export * from "./foo.ts"` clears up the knip report. So it seems knip perfectly finds the file, but in this specific TS config does not follow extensionless import / export.
Using `import { x } from "./foo"` (and re-exporting the constant later) (instead of immediate re-export) still incorrectly lists `foo.ts` as unused.

**Comment by webpro** [comment]
Thanks for the report, but I don't seem to be able to access the repro.

**Comment by Jym77** [comment]
Sorry. I've fixed the permissions (hopefully…)
(I don't know much about codesandbox, but is it possible to have the links from knip's doc to pre-include most of the needed sharing options?)

**Comment by webpro** [comment]
I'm seeing both `foo.js` and `foo.ts` in the same directory, is that intentional?

**Comment by Jym77** [comment]
Ah 💡 So you're saying that `export * from "./foo"` resolves as `foo.js` and thus considers `foo.ts` as ignored?

It is indeed my setup to keep everything in the same directory. This is for a library building and `npm publish` takes care of only bundling the `*.js` and `*.d.ts` files, so I don't need a separate `dist` directory.

**Comment by webpro** [comment]
> Ah 💡 So you're saying that `export * from "./foo"` resolves as `foo.js` and thus considers `foo.ts` as ignored?

Yeah, module resolution can only resolve to a single file, so the other will be ignored. There was a refactoring in module resolution, which was breaking for you for this reason.

> It is indeed my setup to keep everything in the same directory. This is for a library building and `npm publish` takes care of only bundling the `*.js` and `*.d.ts` files, so I don't need a separate `dist` directory.

This is not common afaic, might be confusing for consumers of your lib. I would recommend to separate source and build/distribution artifacts.

Either way, it confuses Knip as it wants only source files. It supports both JS and TS so what's truth here?

**Comment by Jym77** [comment]
🤔 At least I understand where the problem comes from and why it's messy (modules resolution**S** in JS is 🙄).

Maybe it is indeed time for a long overdue overhaul of my library structure… The setup form 2017 might not make that much sense now 😖

**Comment by webpro** [comment]
Let's blame TypeScript for not setting the default value of `outDir` to e.g. `./dist/` :)

Going to close this one as "wontfix" or "invalid".

**Comment by bgmort** [comment]
I just spent a few hours trying to get knip working correctly on a project before finally figuring out that compiled .js files were causing typescript files to be considered unused. I think it would make sense to at least offer on option that can be set so that if a .js file is considered used, and there's a corresponding .ts file with the same name next to it, to consider the .ts file to be used as well, if not for that to be the default behavior.

If that's not going to happen, please at least add a mention about this behavior to the documentation.

Now that it's working for me, it's working beautifully and I am really excited to use it. Thank you for this amazing tool!

**Comment by bgmort** [comment]
Also, I think this is not an uncommon pattern in typescript-powered node server code, as there's no need for a bundler, only to convert source files from .ts to .js, and the .js files can just be .gitignored and left in place.
