### ISSUE TITLE
ts-jest reported as unused after renaming jest.config.js → jest.config.mjs

### ISSUE THREAD

**Issue by danvk** [webpro-nl/knip#675]
knip 5.17.4

Here's my Jest config file:

```ts
/** @type {import('ts-jest').JestConfigWithTsJest} */
export default {
  preset: 'ts-jest',
  testEnvironment: 'node',
};
```

When I rename this from `jest.config.js` → `jest.config.mjs`, knip starts complaining that `ts-jest` is an unused devDependency. My guess is that it's not looking for a `jest.config.mjs` file?

**Comment by webpro** [comment]
It should: https://knip.dev/reference/plugins/jest

Looks like the implementation is a bit naive: https://github.com/webpro-nl/knip/blob/main/packages/knip/src/plugins/jest/index.ts#L43-L45

**Comment by geigerzaehler** [comment]
Hi @danvk. I tried to reproduce the issue but I wasn’t able to. Could you post `package.json` and the node version for a minimal reproduction of the issue? Here’s my attempt to reproduce the issue: <https://stackblitz.com/edit/stackblitz-starters-p9sgy1?file=jest.config.mjs>. Running `npx knip` finds no issues.

**Comment by danvk** [comment]
It's here: https://github.com/danvk/webdiff/tree/main/ts

But… looking at this again, it seems clear that this was my mistake all along. I forgot I had this in my `knip.jsonc`:

```jsonc
  "jest": {
    "config": ["jest.config.js"]
  }
```

So of course knip was looking in the wrong place! 🤦‍♂️ Sorry for the false alarm.
