### ISSUE TITLE
picomatch error

### ISSUE THREAD

**Issue by g-raman** [webpro-nl/knip#685]
Experimenting with knip on a project but I'm getting this errory when trying to run `yarn run knip`

```
C:\Users\user\project\node_modules\knip\node_modules\picomatch\lib\picomatch.js:47
    throw new TypeError('Expected pattern to be a non-empty string');
    ^
```
if i run it with `--debug` i get this:

``` 
{
  cwd: 'C:/Users/user/project',
  tsConfigFile: undefined,
  gitignore: true,
  isDebug: true,
  isProduction: false,
  isStrict: false,
  isShowProgress: false,
  isIncludeEntryExports: false,
  isIncludeLibs: false,
  isIsolateWorkspaces: false,
  isWatch: false,
  tags: [ [], [] ],
  isFix: false,
  fixTypes: [],
  isRemoveFiles: false
}
```
The `tsConfigFile` is undefined for some reason so i ran `yarn run knip --tsConfig ./tsconfig.json`

But the issue persists

**Comment by webpro** [comment]
Please provide an actual reproduction of the issue: https://knip.dev/guides/troubleshooting#minimal-reproduction

Btw, `tsConfigFile` is undefined, but still uses the default `tsconfig.json` if exists.
