### ISSUE TITLE
False positives on Unresolved paths (repro in issue)

### ISSUE THREAD

**Issue by AlemTuzlak** [webpro-nl/knip#689]
# Description
While implementing Knip in our monorepo with Turbo we used the approach of defining tsconfig.json files as provided in the repro, the config is resolved correctly and loaded into the apps but knip complains that the imports don't exist, I believe the reason for this is that knip checks the current folder (core) instead of the root from where the `tsconfig.remix.json` extended the config from.

# Expected behavior
- Knip found no issues

# Actual behavior
Knip found Unresolved imports

https://stackblitz.com/edit/vitejs-vite-keewbt?file=apps%2Fcore%2Ftsconfig.json

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.22.2. See [Release 5.22.2](https://github.com/webpro-nl/knip/releases/tag/5.22.2) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._

**Comment by webpro** [comment]
Thanks for the bug report and repro Alem, should be fixed in v5.22.2!
