### ISSUE TITLE
Report unnecessary exception tags as errors

### ISSUE THREAD

**Issue by shawnmcknight** [webpro-nl/knip#691]
Per https://knip.dev/reference/jsdoc-tsdoc-tags, it's possible to use arbitrary and standard tags to prevent knip from reporting an error for a symbol.

As I review other issues and comments, I see concerns regarding this usage of bypassing knip and generally recommending against it. Hopefully, what I am suggesting here will align with that concern.

There are situations where I am currently seeing knip errors reported in our repo and its based on partially completed code where the full solution is still a work in process. Basically, these errors are correctly reported, but there remains more work to be done to start consuming those symbols. This doesn't align perfectly with any tags, but `@beta` is probably the closest. This type of error would make it difficult to enable knip as a CI gate so encouraging the use of a tag would be appropriate here. However, that could lead to the opposite problem -- unnecessary tags remaining in the codebase after the issue has been rectified.

What I'd like to see is a mechanism where the use of an ignored tag could itself be reported as an error in knip when the tag itself is no longer necessary. This would align with prior art such as:
- [@ts-expect-error](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments) - If the directive is unnecessary then the directive is an error
- eslint [report-unused-disable-directives](https://eslint.org/docs/latest/use/configure/rules#report-unused-eslint-disable-comments) - Will be reported as an error by eslint if the directive is no longer necessary (and is autofixable!)

It's also possible that this could be taken further to discourage the use of tags for lengthy periods of time. There are many variants of this type of eslint plugin, but eslint-plugin-unicorn has a rule [expiring-todo-comments](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/expiring-todo-comments.md#add-expiration-conditions-to-todo-comments) which trigger errors if a todo has gone beyond its designated timeframe. That concept lines up well with the scenario I'm describing where additional development is necessary to consume the symbols that knip is reporting as errors. Something like `@knipignore - 2024-08-01` would imply that the tag will be excluded from being reported as an error until that date.

This package is really excellent work! Thanks!

**Comment by webpro** [comment]
Absolutely, thanks for bringing this up.

Basically, we would need to move [this line](https://github.com/webpro-nl/knip/blob/2efa8fd2b666031667e06232b4d45aaa82496713/packages/knip/src/index.ts#L439) down to [this block](https://github.com/webpro-nl/knip/blob/main/packages/knip/src/index.ts#L494-L504) and add an issue to the issue collector, skip the export to ignore, or add an item to the configuration hints.

There will be a small performance penalty, but I'd say it's def worth it.

One could argue it should be an error (non-zero exit code) and not just a configuration hint (greyed out and does not affect exit code), but perhaps it's a good first step.

I'd need to read up a bit more on the extensions you're describing, but it sounds interesting.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.23.0. See [Release 5.23.0](https://github.com/webpro-nl/knip/releases/tag/5.23.0) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._

**Comment by shawnmcknight** [comment]
Hey @webpro -- thanks for jumping on this so quickly!

I'm trying to test it out right now and I'm not seeing the configuration hints as I expected.

I found various symbols that were being consumed elsewhere and I added a jsdoc tag of `@knipignore` to them and then ran knip with `--tags=-knipignore`. When running, there is no output on the reporter for those symbols that are being used but ignored.

I debugged through and when it gets to the reporter the `tagHints` set is empty, so the problem is not in reporting but rather in collection.

I debugged further up the chain in `index.ts` and set a conditional breakpoint to break when `isIgnored` is true. That triggered as expected for the symbol that had the tag. However, at the `if (!isIgnored && importsForExport) {` line, it skips everything in that block because `isIgnored` is true. The logic to add the tag hint is nested in that block, so it's being bypassed completely.

This isn't working as I expected so I suspect one of the following:
1. I'm not running something correctly
2. Our wires got crossed up and what I was suggesting and what you thought I was suggesting weren't the same
3. The code isn't working as expected

I can create a reproduction if that helps, so let me know. Thanks!

**Comment by webpro** [comment]
I'm going to pick nr 3! I screwed up. I was testing this with another repo and basically two bugs resulted in output looking correct in that repo. Because it's quite the repo and in my enthusiasm I didn't even add tests, etc.

Your debug session was good, but I think the cause was slightly different (there was another `collector.addTagHint` down below; which seems to work because of some `+internal,-knipignore` miracle).
