### ISSUE TITLE
graphql-codegen plugin doesn't handle plugins with plugin-specific config

### ISSUE THREAD

**Issue by CensoredUser** [webpro-nl/knip#692]
The graphql-codegen plugin doesn't seem to correctly detect codegen plugins defined in the config using the "[plugin level](https://the-guild.dev/graphql/codegen/docs/config-reference/config-field#plugin-level)" configuration. 

I noted this on [ee83151c812258c04931f231fa8315fb405d2979](https://github.com/webpro-nl/knip/commit/ee83151c812258c04931f231fa8315fb405d2979#commitcomment-143405155), which actually introduced a test case with the data required to verify this use-case - in the fixture data added in the commit, the `add` plugin is declared, but is not detected by knip.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.22.3. See [Release 5.22.3](https://github.com/webpro-nl/knip/releases/tag/5.22.3) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._

**Comment by webpro** [comment]
Thanks @CensoredUser! Good stuff.
