### ISSUE TITLE
False positives on Github CI with binaries + postcss inconsistency 

### ISSUE THREAD

**Issue by AlemTuzlak** [webpro-nl/knip#694]
Morning Lars!
So there are a few false positives that I can't figure out why they happen, if you run `pnpm knip` here:
https://stackblitz.com/~/github.com/AlemTuzlak/vitejs-vite-keewbt
There are a few surprising things for me:
1. flyctl is reported as unexisting binary, when I remove the `fi` from the yaml file on line 40 it works but it's not a valid bash script anymore
2. postcss and autoprefixer reports ARE reported in the `docs` but NOT in the `core-application`, the setup is more or less identical
3. There is a false positive with apps/docs/app/components/plugins/Details.tx, it's used but reported as unused

**Comment by webpro** [comment]
1. In GitHub Actions, Knip expects binaries to be installed through regular package management (except for the [default ignored ones](https://github.com/webpro-nl/knip/blob/main/packages/knip/src/constants.ts#L28-L75)). My guess is that the `flyctl` binary comes with `superfly/flyctl-actions/setup-flyctl`, which Knip does not know/understand. Recommendation: add `flyctl` to `ignoredBinaries`.
2. The `postcss` dependency is not listed in `package.json`, so doesn't seem like a false positive? Alternatively, you could use the recommendation I gave in https://github.com/webpro-nl/knip/issues/338#issuecomment-2185278111.
3. Knip does not add files to the dependency graph through `readFileSync()` calls. Recommendation: such files can be manually added as `entry` files.

**Comment by AlemTuzlak** [comment]
@webpro Thank you so much, I've done the following for future reference:
1. Added to ignored binaries
2. OMG I Forked a repo and didn't notice that, thank you! Installing postcss fixes this
3. So the interesting bit was that this "details" false positive was not imported unlike all the other plugins in the folder to a specific file hence the issue. So it's not a false positive rather it indeed wasn't being loaded anywhere and `readFileSync` indeed does not pick it up

For the 1 though, why would it work without the closing `fi`, does it skip the file because it's an incorrect bash command?

**Comment by webpro** [comment]
Great!


> For the 1 though, why would it work without the closing `fi`, does it skip the file because it's an incorrect bash command?

Perhaps Knip's script parser trips over the invalid script. Then the `flyctl` binary doesn't reach the Knip mechanics at all and there's nothing to report. The `--debug` flag should show this, though.
