### ISSUE TITLE
[jest] support nested jest config files

### ISSUE THREAD

**Issue by aramissennyeydd** [webpro-nl/knip#702]
👋 I'm trying to have our Rush monorepo use knip and running into a few things that are probably Rush specific. One of them is that we place our jest configs into a nested directory, `config/jest.config.json`. It looks like knip then tries to resolve all files relative to that `config/*` prefix causing something like `setupFiles: ['<rootDir>/config/jest.setup.js']` to resolve to `/config/config/jest.setup.js`. 

On the Rush side, [they end up setting rootDir to build folder deep in their tooling](https://github.com/aramissennyeydd/rushstack/blob/9f1a448d15297b81602f04656aa40db59713f351/heft-plugins/heft-jest-plugin/src/JestPlugin.ts#L888-L895), which means it isn't available outside of that context.

I think the intention with the knip code is to handle nested directories that have a root level jest config. What would be a good way to handle the Rush nested config folder? Maybe an additional config option, `rootDir`, that we could set to `"../"` or `"/"` to define where we resolve the root directory from?

Happy to submit a fix for this!

**Comment by webpro** [comment]
Indeed, the `<rootDir>` is the directory of the config file (`config/jest.config.json`).

Knip does not support custom options for plugins, so I'm not sure what we can do here at this point. It's also actually more of an issue with Rush, right? One option is to muse `jest.config.js` and then resolve and set the absolute path to `jest.setup.js`.

**Comment by aramissennyeydd** [comment]
@webpro Thanks for the quick response! Yeah, it's definitely a Rush oddity. It's also a little out of spec for Jest, which also indicated that the config file should be in the root of the package.

I'll take a look at workarounds on our side, I think I might also be able to just declare `rootDir` in the jest config which will get overwritten by rush but could be used by knip.

**Comment by aramissennyeydd** [comment]
Was able to get this working pretty easily with the following function that runs before we run knip,
```
async function updateJestConfig(packageDir) {
  const jestConfigPath = path.join(packageDir, 'config', 'jest.config.json')
  if (!existsSync(jestConfigPath)) {
    return
  }
  const jestConfig = JSON.parse(await readFile(jestConfigPath))
  jestConfig.rootDir = '..'
  await writeFile(jestConfigPath, JSON.stringify(jestConfig, null, 2))
}
```
