### ISSUE TITLE
False negative when name is used as property

### ISSUE THREAD

**Issue by neelmraman** [webpro-nl/knip#704]
Hi, thanks again for your work on this project and sorry for the numerous bug reports over the past few days. 

I found a new issue where exports are not marked as unused if the same name is also used as a property (and I imagine there could be other contexts as well that similarly mask the usage of the export). [Here](https://codesandbox.io/p/devbox/modest-dawn-qwfgq2-forked-6335nq) is a repro.

**Comment by webpro** [comment]
Yeah, duplicate names are support by TypeScript, but not Knip unfortunately.

**Comment by webpro** [comment]
Until this is reported more often as problematic, won't fix.
