### ISSUE TITLE
All typescript interface files reported as Unused exported types

### ISSUE THREAD

**Issue by Xor767** [webpro-nl/knip#709]
Hi guys! 
Since Knip version **5.23.0**, all interface files like the following one are reported as **Unused exported types** : 
```
export default interface MyInterface {
  id: number;
  label: string;
}
```

Even if they're used like that: 
`import MyInterface from '@/scripts/interfaces/myInterface.ts';`

that wasn't the case with Knip version **5.22.3**.
any idea?

**Comment by webpro** [comment]
Not sure why this change occurred in your situation. Please provide an actual reproduction so I can look into it properly.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.23.3. See [Release 5.23.3](https://github.com/webpro-nl/knip/releases/tag/5.23.3) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._

**Comment by webpro** [comment]
Suddenly I realized something I've refactored last week. You can't default-export enums and types, but interfaces are OK. Should be fixed now. Thanks for reporting this.

**Comment by Xor767** [comment]
Thanks a lot 💪
