### ISSUE TITLE
Unused assets are not reported

### ISSUE THREAD

**Issue by OoDeLally** [webpro-nl/knip#710]
Not sure if that's a feature or a bug.

I use Vite + React and I import my images as such:
```ts
import myImagePng from '@/assets/my-image.png'

//...
<img src={myImagePng} />
```

Now my Knit config is as such

```ts
import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  entry: ['src/main.tsx'],
  project: ['**/*.{js,ts,jsx,tsx,png,svg}'],
};

export default config;
```

I have plenty of `png` unused images in my `src/assets/`, and none are reported.

When running Knip with `--debug` I can see it correctly lists my assets as project files, even the unused ones:

```
[.] Project paths (131)
[
  '/home/user/myproj/eslint.config.js',
  '/home/user/myproj/knip.ts',
  '/home/user/myproj/src/App.tsx',
  '/home/user/myproj/src/assets/AFK.png',
  '/home/user/myproj/src/assets/ResponseCode/418.png',
  '/home/user/myproj/src/assets/chevronleft.svg',
  '/home/user/myproj/src/assets/clock-alert.svg',
  '/home/user/myproj/src/assets/games/asphalt.png', // Unused but not reported
...
```

Does Knip have a builtin exclusion of non-text files?

**Comment by webpro** [comment]
It's a feature indeed, expected behavior.

See [foreign file extensions](https://github.com/webpro-nl/knip/blob/main/packages/knip/src/constants.ts#L81-L103). Also see https://knip.dev/features/compilers.

Now, if you want to pull png files into the dependency graph you can try something like this:

```
{
  compilers: {
    png: () => ''; // dummy compiler, return empty string
  }
}
```

With this in place, you don't need to add such extensions to the `project` pattern(s).

**Comment by OoDeLally** [comment]
I  see, thank you!
Wouldn't it be great to have as a feature that Knip does not exclude e.g. `png` if they are explicited in the `project` pattern?
For now I'll use your suggested method.
Thank you

**Comment by webpro** [comment]
> Wouldn't it be great to have as a feature that Knip does not exclude e.g. `png` if they are explicited in the `project` pattern?

Maybe! Not sure how clear of an API that is, but also it makes sense.
