### ISSUE TITLE
Vite plugin should activate when vitest present in deps

### ISSUE THREAD

**Issue by aryzing** [webpro-nl/knip#712]
The vite plugin only loads when vite is a dependency. However, vitest may be used without explicitly installing vite. If vitest is installed, packages used in vite.config.ts should not be marked as unused even if vite is not explicitly installed.

**Comment by webpro** [comment]
Agreed, should be fixed in [v5.24.0](https://github.com/webpro-nl/knip/releases/tag/5.24.0).
