### ISSUE TITLE
Warning "The CJS build of Vite's Node API is deprecated"

### ISSUE THREAD

**Issue by crystalfp** [webpro-nl/knip#714]
The issue can be reproduced e.g., by the #619 provided project.
```
PS D:\vue-project> knip
Analyzing workspace ....
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-depr
. . .
```
It is a minor annoyance, but what could be done to remove this warning?
Thanks!
mario

**Comment by webpro** [comment]
See https://knip.dev/reference/known-issues
