### ISSUE TITLE
package.json scripts parsing issue when using --require in NODE_OPTIONS env variable

### ISSUE THREAD

**Issue by jraoult** [webpro-nl/knip#715]
When knip v5.24.1 tries to parse one of my package.json's scripts, I get the following error

```bash
file:///[...]/node_modules/knip/dist/binaries/index.js:12
        if (identifier.startsWith('http'))
                       ^

TypeError: identifier.startsWith is not a function
    at file:///[...]/node_modules/knip/dist/binaries/index.js:12:24
    at Array.map (<anonymous>)
    at getDependenciesFromScripts (file:///[...]/node_modules/knip/dist/binaries/index.js:11:28)
```

I managed to reduce to this:

```json
{
  "scripts": {
     "repro": "NODE_OPTIONS='--require a --require b' a-custom-command"
  }
}
```

If I remove the second `--require` or if I write' node' instead of ` a-custom-command`, there is no error.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.24.2. See [Release 5.24.2](https://github.com/webpro-nl/knip/releases/tag/5.24.2) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._

**Comment by webpro** [comment]
Thanks for the report, @jraoult! Should be better now.

**Comment by jraoult** [comment]
Brilliant @webpro. Thanks for addressing it.
