### ISSUE TITLE
unused exports within '.vue' files

### ISSUE THREAD

**Issue by blake-newman** [webpro-nl/knip#733]
Currently `knip` only reports unused exports within `.ts/tsx` files. 

It would be a useful feature to also expose unused exports that are embedded within `.vue` files.

`.vue` files can expose additional exports. For brevity the example shows a type within a component that may be used internally, but mistakenly marked as a export.

```vue
<script lang="ts">
export type Size = 'small' | 'medium'

// ...
 
</script>
```

**Comment by webpro** [comment]
This why you can override with an actual compiler, ideally the one you already have local to your project and thus the same version of e.g. Vue.

Also see https://knip.dev/features/compilers

Perhaps the docs should have such an example, but the idea is: text in, text out. I'll try to add example(s) when I can.

**Comment by blake-newman** [comment]
@webpro cheers for the information, i'll take a look at this feature. I did originally look into but i could only see 'imports' being extracted so assumed it wasn't intended for extracting exports. 

Is this something the team are open to contributions for the default compiler (dependent on overall performance costs).

**Comment by blake-newman** [comment]
For those interested in a naive solution, which wil:
- extract the content of script blocks, including `src` attribute.
- extract the imports of style blocks, including `src` attribute.

```ts
import type { KnipConfig } from 'knip'
import { parse, type SFCScriptBlock, type SFCStyleBlock } from 'vue/compiler-sfc'

function getScriptBlockContent(block: SFCScriptBlock | null): string[] {
  if (!block) return []
  if (block.src) return [`import '${block.src}'`]
  return [block.content]
}

function getStyleBlockContent(block: SFCStyleBlock | null): string[] {
  if (!block) return []
  if (block.src) return [`@import '${block.src}';`]
  return [block.content]
}

function getStyleImports(content: string): string {
  return [...content.matchAll(/(?<=@)import[^;]+/g)].join('\n')
}

const config = {
  compilers: {
    css: getStyleImports,
    vue: (text: string, filename: string) => {
      const { descriptor } = parse(text, { filename, sourceMap: false })
      return [
        ...getScriptBlockContent(descriptor.script),
        ...getScriptBlockContent(descriptor.scriptSetup),
        ...descriptor.styles.flatMap(getStyleBlockContent).map(getStyleImports)
      ].join('\n')
    },
  },
  // rest of configuration
} satisfies KnipConfig

export default config
```

**Comment by webpro** [comment]
Thanks for sharing @blake-newman.  Isn't there an easier way to render the `.vue` file in one `render()` call or something to JavaScript?

Appreciate the solution here, but would be great to have an easier example in the docs.

**Comment by webpro** [comment]
Added this to the docs: https://knip.dev/features/compilers#vue. Maybe can iterate and improve, but this seems like a copy-pasteable solution :)

Thanks again!

**Comment by yishuolin** [comment]
Hi @webpro, it seems that the `getStyleImports` function is missing in the docs.

**Comment by webpro** [comment]
I see. You mean this, right?

https://github.com/webpro-nl/knip/blob/main/packages/docs/src/content/docs/features/compilers.md?plain=1#L125

Any chance you could fix this in a pull request?

**Comment by yishuolin** [comment]
Thanks for the quick response. I can create a pull request later.
