### ISSUE TITLE
Monorepo package dev dependency binary used in GitHub actions workflow reported as unlisted

### ISSUE THREAD

**Issue by with-heart** [webpro-nl/knip#735]
### Reproduction url

https://stackblitz.com/edit/github-e9sos1?file=packages%2Fclient%2Fpackage.json

### Description of the issue

When the binary of a dev dependency of a package in a monorepo is used in a GitHub actions workflow (using `yarn --cwd`), the binary is reported as unlisted.

`packages/client/package.json`:
```
  "scripts": {
    "svelte-check": "svelte-check --workspace test"
  },
  "devDependencies": {
    "svelte-check": "^3.2.0"
  },
```

`.github/workflows/node.yml`:
```
      - name: Svelte Check
        run: yarn --cwd packages/client svelte-check
        shell: bash
```

Output:
```
❯ yarn knip
yarn run v1.22.19
$ knip
Unlisted binaries (1)
svelte-check  .github/workflows/node.yml
error Command failed with exit code 1.
```

For reference, I ran into this issue as part of https://github.com/statelyai/xstate/pull/4974. Planned workaround is to add `.github/workflows/node.yml` to `ignore` for now.

I would expect no error to be reported.

**Comment by with-heart** [comment]
Not unfortunate, that's totally understandable! Do you think it'd be worth adding a note in the docs about this somewhere? I'd be happy to tackle that if so

**Comment by webpro** [comment]
Going to close with the release of v5.34.0

**Comment by with-heart** [comment]
Thanks for everything you do @webpro ❤️

**Comment by webpro** [comment]
Appreciate that!
