### ISSUE TITLE
cannot read the ESLint written in JS.

### ISSUE THREAD

**Issue by SEOKKAMONI** [webpro-nl/knip#737]
### Reproduction url

https://github.com/toss/suspensive/tree/main/configs

### Description of the issue

Our ESLint rules are located in the configs folder linked above.

We want to check which dependencies are being used and which are not being used in the packages within the configs folder using knip. However, it is not working as expected.

I would like to know if this is due to a configuration error on my part or a bug in knip. If it is due to a configuration error, I would appreciate it if you could suggest a solution.

### knip.json
```json
{
  "$schema": "https://unpkg.com/knip@5/schema.json",
  "ignore": ["**/*.config.?js"],
  "ignoreWorkspaces": ["docs/**", "websites/**"],
  "ignoreDependencies": ["react-dom", "@types/react-dom", "@suspensive/test-utils"],
  "workspaces": {
    ".": {
      "ignoreDependencies": ["prettier-plugin-tailwindcss"]
    },
    "configs/*": {
      "entry": ["**/*.js"]
    }
  }
}
```

### Terminal
<img width="540" alt="image" src="https://github.com/user-attachments/assets/543844f6-625b-4b2e-9629-c500c93adfd5">

**Comment by webpro** [comment]
The ESLint config files aren't regular entry files. You can try something like this:

```json
{
  "$schema": "https://unpkg.com/knip@5/schema.json",
  "workspaces": {
    "configs/eslint-config*": {
      "eslint": {
        "config": [".eslintrc.cjs", "*.js"],
      }
    }
  }
}
```

This configures the ESLint plugin to also use the `*.js` files as ESLint config files and then they'll be parsed as such. Seems like there's no way for Knip to figure this out automatically.
