### ISSUE TITLE
Knip doesn't parse arguments of `yarn run --top-level` correctly

### ISSUE THREAD

**Issue by Jym77** [webpro-nl/knip#739]
### Reproduction url

[Sandbox](https://codesandbox.io/p/devbox/t3l78m?migrateFrom=c7ntv3&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyy65onq0006356jqva99u87%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyy65onq0002356j39ygwee6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyy65onq0004356jmhct5v4q%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyy65onq0005356jmz4mwbv3%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyy65onq0002356j39ygwee6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyy65onq0001356jh7uf6v0f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%257D%255D%252C%2522id%2522%253A%2522clyy65onq0002356j39ygwee6%2522%252C%2522activeTabId%2522%253A%2522clyy65onq0001356jh7uf6v0f%2522%257D%252C%2522clyy65onq0005356jmz4mwbv3%2522%253A%257B%2522id%2522%253A%2522clyy65onq0005356jmz4mwbv3%2522%252C%2522activeTabId%2522%253A%2522clyy65s3v000d356j6v392pmw%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522clyy65s3v000d356j6v392pmw%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clyy65onq0004356jmhct5v4q%2522%253A%257B%2522id%2522%253A%2522clyy65onq0004356jmhct5v4q%2522%252C%2522activeTabId%2522%253A%2522clyy65onq0003356jap54cqff%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyy65onq0003356jap54cqff%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522NEW_TERMINAL%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clyy660z8000z356j4813zaq5%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Description of the issue

In a monorepo setting, a workspace script invoking a top-level script which takes positional parameters gets these parameters incorrectly interpreted as scripts (and reported) by knip

---
Top-level package.json:
```json
"scripts": {
    "echo": "echo"
  },
```
Here, the `echo` script just calls the `echo` shell command, which takes extra parameters on the command line.

Workspace (`packages/shared`) package.json:
```json
"scripts": {
    "foo": "yarn run --top-level echo hello"
  }
```
This uses the `--top-level` flag which seems to not exist in yarn 1. It simply calls the top-level script, providing a parameter to it.

When running (from the toplevel) `yarn workspace @monorepo/shared run foo`, or (from the workspace directory) `yarn foo`, I get the correct behaviour (display `hello` in the terminal).

When running `yarn knip`, I get:
```
Unlisted binaries (2)
...
hello  packages/shared/package.json
```
So, it seems that knip is interpreting the command as running `echo` and `hello` scripts.
Adding a `hello` script inside the package does remove the reporting. Adding one at toplevel doesn't.

This may be related to https://github.com/webpro-nl/knip/issues/735 but I believe it is different.

---
I was not able to reproduce this in a basic (single workspace) setting; Without the `--top-level` option (and using an `echo` script in the workspace), `hello` is not reported, so the option may have something to do with it.

Somehow, removing the `echo` script from the top-level is not reported. Maybe knip interpretes `yarn run --top-level echo hello` as being an option `--top-level echo` and calling script `hello` (instead of option `--top-level` and calling script `echo` with parameter `hello`).

**Comment by Jym77** [comment]
> > This may be related to #735 but I believe it is different.
> 
> Why do you think it's different?

#735 (and the linked #433) seemed related to Github action on first read.
Looking more, #735 may have something to do with parsing CLI arguments, but there knip correctly detects the script name, and incorrectly doesn't find it (as it looks in the wrong directory). Here, knip incorrectly detects the script name, and ("correctly") reports it as missing (that script indeed does not exist).

But indeed, they may both boil down to the fact that `--foo bar` is effectively discarded while in both cases (`--cwd`, `--top-level`) it actually has a meaning that should impact knip behaviour.

**Comment by webpro** [comment]
Doing some refactoring that unlocks features like this. In the next version, Knip will support `--top-level` and `--cwd [dir]` for Yarn commands. You could try an early version if you like:

```
yarn add -D https://pkg.pr.new/knip@f1349c2
```

**Comment by webpro** [comment]
Going to close with the release of v5.34.0
