### ISSUE TITLE
Most files are marked as unused when they actually are used

### ISSUE THREAD

**Issue by erictompkins** [webpro-nl/knip#741]
### Reproduction url

https://github.com/erictompkins/knip-issue

### Description of the issue

I'm pretty sure that this an issue with my setup, but when I run knip all but two of the files in my project are marked as unused.

I have tried a variety of configuration options with no success.

Also, most of the dependencies are marked as unused.

In the `.eslintrc.cjs` file there is an import resolver configuration.

```js
'import/resolver': {
      typescript: {
          project: 'js',
      },
  },
```

I'm wondering if thats an issue because all of my `@import` statements for project files don't use the "js" path in the import.

Thank you for any help you can provide.

**Comment by webpro** [comment]
When the `tsconfig.json` is pulled in from `js/tsconfig.json` for the TypeScript plugin, that is then only used to extract dependencies from that config. Knip does not resolve the `baseUrl` that way.

My recommendation is to start with this:

```
knip --tsConfig js/tsconfig.json
```

An alternative is indeed to use `paths`, yet they should match the import specifiers, such as `lib/...`, etc like so:

```jsonc
{
  "paths": {
    "components/*": ["js/components/*"],
    "lib/*": ["js/lib/*"],
    // etc.
  }
}
```

But the first recommendation is easier and better.

**Comment by erictompkins** [comment]
Thank you for your help with this.

Adding `--tsConfig js/tsconfig.json` to the `knip` call worked, but thats a little unexpected.

In the `knip.json` configuration file I included what I thought was the correct configuration to specify the typescript file:

```json
{
  "$schema": "https://unpkg.com/knip@5/schema.json",
  "entry": ["js/app-entry/main/index.tsx"],
  "project": ["js/**/*.{js,ts,tsx}"],
  "typescript": {
    "config": ["js/tsconfig.json"]
  },
  "paths": {
    "js": ["js"],
    "js/*": ["js/*/**"]
  }
}
```

Isn't this the right way to set the TypeScript configuration file path?

```
"typescript": {
        "config": ["js/tsconfig.json"]
    }
```

If I debug knip with `-d` the I get the following:

```
TypeScript config file paths (1)
[ '/documents/test/js/tsconfig.json' ]
```
(file path changed for this comment)

That shows when I include `--tsConfig js/tsconfig.json`, or have the `typescript` configuration in the `knip.json` file. The only time that doesn't show is if both of those parameters are missing. But the knip run only works with `--tsConfig js/tsconfig.json`.

**Comment by erictompkins** [comment]
Also, if I try to change `knip.json` to `knip.js` the configuration doesn't work. 

My knip.js file is:

```js
export default {
    entry: ['js/app-entry/main/index.ts'],
    project: ['js/**/*.{js,ts,tsx}'],
    typescript: {
        config: ['js/tsconfig.json'],
    },
}
```

With that configuration all the files are marked as unused.

But if I use `knip.json` instead it works. My knip.json is:

```json
{
    "$schema": "https://unpkg.com/knip@5/schema.json",
    "entry": ["js/app-entry/main/index.tsx"],
    "project": ["js/**/*.{js,ts,tsx}"],
    "typescript": {
        "config": ["js/tsconfig.json"]
    }
}
```

**Comment by erictompkins** [comment]
Thank you for that explanation. That helps a lot. 

Is it possible for the documentation to get updated? The [Typescript](https://knip.dev/reference/plugins/typescript) plugin page shows an example of setting the `config` value, which implies that it sets where the typescript configuration file comes from.
