### ISSUE TITLE
Knip doesn't resolve imports in Nuxt projects

### ISSUE THREAD

**Issue by BMFreed** [webpro-nl/knip#748]
### Reproduction url

https://codesandbox.io/p/devbox/priceless-aryabhata-zl8s4x?file=%2Fapp.vue%3A8%2C8

### Description of the issue

Knip doesn't seem to be working correctly in Nuxt projects. Here is an example when we import a function in app.vue:
![image](https://github.com/user-attachments/assets/536950ee-eaaf-4e54-8aeb-a2d26f9fa967)

And that same function is then reported by Knip as an unused file, while the import is unresolved:
![image](https://github.com/user-attachments/assets/5cefc171-5afb-44df-a58e-6057a681bc43)

For some reason, Knip doesn't resolve Nuxt paths properly.

Running `pnpm knip --tsConfig .nuxt/tsconfig.json` or copying the `tsconfig.json` from `.nuxt` folder into the main folder does **not** fix the issue.

**Comment by webpro** [comment]
The issue is that `baseUrl` isn't set in either of the `tsconfig.json` files.

For now you can do this:

```jsonc
{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "baseUrl": ".nuxt"
  }
}
```

Or wait until the next release of Knip, this will have a patch to handle it for you.

**Comment by BMFreed** [comment]
> The issue is that `baseUrl` isn't set in either of the `tsconfig.json` files.
> 
> For now you can do this:
> 
> ```js
> {
>   // https://nuxt.com/docs/guide/concepts/typescript
>   "extends": "./.nuxt/tsconfig.json",
>   "compilerOptions": {
>     "baseUrl": ".nuxt"
>   }
> }
> ```
> 
> Or wait until the next release of Knip, this will have a patch to handle it for you.

It worked! Thank you so much!

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.27.1. See [Release 5.27.1](https://github.com/webpro-nl/knip/releases/tag/5.27.1) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._

**Comment by BMFreed** [comment]
Unfortunately, there is another issue regarding Nuxt. If Vue isn't listed in dependencies or devDependencies - knip doesn't seem to enable the Vue plugin. In the [reproduction URL](https://codesandbox.io/p/devbox/priceless-aryabhata-zl8s4x?file=%2Fapp.vue%3A8%2C8) I tried to enable the Vue plugin manually within knip.json by setting "vue" to true and to the default (as mentioned [here](https://knip.dev/reference/plugins/vue)) config value, but this doesn't work.

Can this be fixed without needing to add vue to dependencies or devDependencies?

Thanks in advance!

**Comment by webpro** [comment]
> Can this be fixed without needing to add vue to dependencies or devDependencies?

Like you said, you can enable the Vue plugin manually. You can use `--debug` to see whether the plugin is enabled or not, and what it finds. I'd need a reproduction to look into it (please file a new issue then).
