### ISSUE TITLE
Plz know my ‘tsconfig.xyz.json’

### ISSUE THREAD

**Issue by jessekrubin** [webpro-nl/knip#757]
I have many tsconfig files. They often “extends” one another. There are often unnecessary/duplicate fields. The redundant tsconfig options could totally be knipped.

(My current turd of a bash+python script is calls “tsc —showconfig/print-config” a bunch of times and is called “tsconfix” (if you need a name for a command))

**Comment by webpro** [comment]
Sorry, this is really out of scope for Knip.

**Comment by jessekrubin** [comment]
Bummer
