### ISSUE TITLE
🔄 Issue links are broken

### ISSUE THREAD

**Issue by lishaduck** [webpro-nl/knip#760]
### Reproduction url

n/a

### Good version

n/a

### Bad version

n/a

### Description of the regression

I tried to file a feature request, but you can't anymore.
I blame dbfefa316c6710c1179a0f0c2ca762525ea32140

**Comment by lishaduck** [comment]
Yup: https://github.com/webpro-nl/knip/blob/dbfefa316c6710c1179a0f0c2ca762525ea32140/.github/ISSUE_TEMPLATE/03-feature_request.yaml

Big red error there. You want `type: input`, not `type:markdown`.

**Comment by lishaduck** [comment]
For reference, my feat request was going to be adding in support for TS 5.5 `@import` comments. :)
Both becuase I leave them lying around everywhere, and they should be considered dependencies.

**Comment by webpro** [comment]
Thanks @lishaduck! Should be fixed now.

Import comments should work (eg this fixture has some: https://github.com/webpro-nl/knip/blob/main/packages/knip/fixtures/jsdoc/index.ts) - feel free to open an issue with a reproduction.
