### ISSUE TITLE
🐛 Soft-linked dependencies are considered unused

### ISSUE THREAD

**Issue by robintown** [webpro-nl/knip#766]
### Prerequisites

- [X] I'm using the latest version
- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://stackblitz.com/edit/github-jj73er

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Description of the issue

I am seeing false positives for dependencies that are soft-linked into node\_modules from somewhere else on the file system. This can happen when using package manager features such as `npm link` to work on an application and a library simultaneously, for instance.

To reproduce: go to the link above and,

```
cd test-1
npm run knip
```

`test-2` is flagged as an unused dependency even though it is imported in index.ts. `test-1/node_modules/test-2` is a soft link to `test-2`.

**Comment by webpro** [comment]
Thanks for the report. Yeah, that makes sense. There's quite some string comparisons/refs to `/node_modules/`. Fixing this would require to actually follow the fs link, etc. Not sure if it's worth fixing this in terms of both code complexity and performance given the use case/situation in which the simplicity fails.

**Comment by webpro** [comment]
Decided to close this as "wontfix", due to reasons described.
