### ISSUE TITLE
Knip doesn't enable Vue plugin in Nuxt 🐛 

### ISSUE THREAD

**Issue by BMFreed** [webpro-nl/knip#770]
### Prerequisites

- [X] I'm using the latest version
- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://codesandbox.io/p/devbox/priceless-aryabhata-zl8s4x?file=%2Fknip.json%3A16%2C2

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Description of the issue

It seems that Knip doesn't enable Vue plugin in Nuxt if Vue isn't explicitly listed in dependencies/devDependencies.
In the [reproduction URL](https://codesandbox.io/p/devbox/priceless-aryabhata-zl8s4x?file=%2Fapp.vue%3A8%2C8) I tried to enable the Vue plugin manually within knip.json by setting "vue" to true and to the default (as mentioned [here](https://knip.dev/reference/plugins/vue)) config value, but this doesn't work.

Can this be fixed without needing to add vue to dependencies or devDependencies?

Thanks in advance!

**Comment by webpro** [comment]
The Vue plugin is enabled, but what we need here is a Nuxt plugin.

**Comment by webpro** [comment]
Oh, it's in the TS config (`"jsxImportSource": "vue"`), so it's a referenced dependency from the perspective of the TypeScript plugin.

For now I'd recommended to add `"vue"` to `ignoreDependencies`.

**Comment by BMFreed** [comment]
> Oh, it's in the TS config (`"jsxImportSource": "vue"`), so it's a referenced dependency from the perspective of the TypeScript plugin.
> 
> For now I'd recommended to add `"vue"` to `ignoreDependencies`.

Thank you for your reply!
This solves the problem with Knip reporting Vue as a missing dependency, but the main issue is that if Vue isn't explicitly listed in dependencies/devDependencies - the Vue plugin isn't enabled, so knip doesn't parse Vue files and reports the file "foo.ts" as unused, although it is imported in the .vue file.

Is there a way to forcefully enable the Vue plugin without installing it in the dependencies?
For now just installing it as a dev dependency is the only workaround I found in order for Knip to parse Vue files :(

**Comment by webpro** [comment]
> knip doesn't parse Vue files

AH I didn't catch that.

> Is there a way to forcefully enable the Vue plugin without installing it in the dependencies?

So the issue is that `vue: true` enables the Vue plugin, but not compiling the Vue files. We can just [add `nuxt` here](https://github.com/webpro-nl/knip/blob/main/packages/knip/src/compilers/vue.ts#L4)

I can whip up a release soon for this.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.27.5. See [Release 5.27.5](https://github.com/webpro-nl/knip/releases/tag/5.27.5) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._
