### ISSUE TITLE
💡 Follow `references` in TS config file.

### ISSUE THREAD

**Issue by Jym77** [webpro-nl/knip#780]
### Suggest an idea for this project

Follow up on #779.

As per [Lars words](https://github.com/webpro-nl/knip/issues/779#issuecomment-2337934349):
> I can imagine there'll be issues since Knip doesn't actively support `references` or `tsconfig.json` files that are not in the workspace root.

[This sandbox](https://codesandbox.io/p/devbox/mdkscf?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0ur3hgr0006356ir8mt1qfo%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0ur3hgr0002356ihrdhv0w4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0ur3hgr0004356itu3v6nng%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0ur3hgr0005356id5x963rl%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0ur3hgr0002356ihrdhv0w4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0ur3hgr0001356iqt12uy96%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A20%257D%255D%257D%252C%257B%2522id%2522%253A%2522cm0w5ct950002356i5nc3kpli%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A24%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A24%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Ftsconfig.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm0w7tf9a0002356iu1brjp2h%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A36%252C%2522endLineNumber%2522%253A1%252C%2522endColumn%2522%253A36%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0ur3hgr0002356ihrdhv0w4%2522%252C%2522activeTabId%2522%253A%2522cm0w7tf9a0002356iu1brjp2h%2522%257D%252C%2522cm0ur3hgr0005356id5x963rl%2522%253A%257B%2522id%2522%253A%2522cm0ur3hgr0005356id5x963rl%2522%252C%2522activeTabId%2522%253A%2522cm0ur3jox000c356i8cvj8j0d%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522cm0ur3jox000c356i8cvj8j0d%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm0ur3hgr0004356itu3v6nng%2522%253A%257B%2522id%2522%253A%2522cm0ur3hgr0004356itu3v6nng%2522%252C%2522activeTabId%2522%253A%2522cm0ur3hgr0003356ix9eaqoel%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0ur3hgr0003356ix9eaqoel%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522NEW_TERMINAL%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522cm0ur3s0e0011356icqrnz0tk%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) shows a setup where the toplevel (workspace root) `tsconfig.json` uses `references` to point to subdirectories that are not workspace roots, and build their artefacts in separate `dist-*` directories. This results in knip not making the link between the build artefact in `dist-foo/foo.js` and the source file in `src/foo/foo.ts` and thus reporting the later as unused.

---
Now, I'm not sure whether this kind of setup is common enough to justify supporting it 😅 I have something similar in my huge legacy code base, but that is maybe very rare (likely is if nobody reported it earlier…)

Additionally, knip does provide a workaround by the mean of carefully crafter post processor to discard a handful of issues. This is not a perfect solution since it will keep skipping the issue even if it became a true positive, but it allows to keep using knip for the other issues.

**Comment by webpro** [comment]
Sorry but that's the same repro.
