### ISSUE TITLE
💡 `ignoreImportsUsedInFiles: []`

### ISSUE THREAD

**Issue by tizmagik** [webpro-nl/knip#782]
### Suggest an idea for this project

It would be great to be able to specify specific files that shouldn't count as "usage" for a particular export.

In one of my projects, if the import is used in a particular file, we don't want it to count as it actually being used because it's a common place to import a long list of them to add some meta data/behavior, but it doesn't mean it will actually be used in the application code.

For example, deleting that specific file and re-running Knip would report the export as unused and that is the sort of the behavior we're looking for.

generated.ts
```ts
/* Generate file with a bunch of exports */
export FOO1 = "123";
export FOO2 = "456";
// ...
```

meta-function.ts
```ts
/* Common place to import all of them and register some meta behavior */
import { FOO1, FOO2 } from './generated.ts';

meta(FOO1, FOO2);
```

app.ts
```ts
/* App code */
import {FOO1} from './generated.ts';

doWork(FOO1);
```

We don't want `FOO2` to be counted as used since it's not referenced by App code.

**Comment by webpro** [comment]
Interesting. It could be implemented, but I wonder if there's enough interest for it.

(note to self: would only work if not using `LS.findReferences`/`--include-libs`)

**Comment by webpro** [comment]
Perhaps you can implement a preprocessor for this? Then you can modify the results any way you like. See https://knip.dev/features/reporters#preprocessors

Going to close this one.
