### ISSUE TITLE
💡 docs should have hover links

### ISSUE THREAD

**Issue by Zamiell** [webpro-nl/knip#783]
### Suggest an idea for this project

Right now, if I hover over a heading in the knip docs, nothing happens.

But with other documentation, such as Docusaurus, React.dev, etc., it shows a chain symbol that you can mouse over and click to change the URL with an anchor to the section that you clicked on, and then you can copy paste the URL to link a specific part of the docs to someone else.

Maybe this seems like a small thing, but it is very important, because it can be non-straightforward to manually compile an anchor link to a section with special characters and so on.

**Comment by webpro** [comment]
That's a nice detail indeed. You could also do this using the side nav on the right, but I've added clickable `#` text on hover.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.30.3. See [Release 5.30.3](https://github.com/webpro-nl/knip/releases/tag/5.30.3) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._
