### ISSUE TITLE
🐛 `vitest.workspace.mts` Not Dectected by Vitest Plugin

### ISSUE THREAD

**Issue by joealden** [webpro-nl/knip#784]
### Prerequisites

- [X] I'm using the latest version
- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

N/A

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Description of the issue

As shown in https://knip.dev/reference/plugins/vitest, `vitest.workspace.ts|js|json` is picked up, but `mjs|cjs|mts|cts` extensions are not. I know for sure that `vitest.workspace.mts` is valid to Vitest, so should we just match the extensions we are looking for for the normal Vitest configs?

**Comment by webpro** [comment]
Yes, that makes sense. Any chance you would be willing to submit a PR to fix that up?

**Comment by joealden** [comment]
@webpro sure! See https://github.com/webpro-nl/knip/pull/785.
