### ISSUE TITLE
🔄 Function `isStartsLikePackageName` should accept scoped packages which starts with `.` or `_` too

### ISSUE THREAD

**Issue by heavybeard** [webpro-nl/knip#789]
### Prerequisites

- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://codesandbox.io/p/sandbox/reverent-sammet-yl9drl

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Good version

5.27.3

### Bad version

5.27.4

### Description of the regression

Thanks to [this commit](https://github.com/webpro-nl/knip/commit/89780376c5e0fffb480408dab2895ca6ec9b7244#diff-3b861313c9e2d00e0d0d56c3e1c3fa533731db0097209dc154f992d823b89621R325) introduced in `5.27.4` version, packages like `@_sh/strapi-plugin-ckeditor` are filtered from `ignoreDependencies` array.

This is causing a circular error with "Unused dependecies" and "Unused item in `ignoreDependencies`"

![image](https://github.com/user-attachments/assets/440eafa9-d3bb-4144-b686-daef8dc75194)

In a quick investigation, I landed in `isStartsLikePackageName` regex that missing `_` and `.` symbols. Underscore and point are valid starting character for scoped packages as npm mention [here](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#:~:text=The%20names%20of%20scoped%20packages%20can%20begin%20with%20a%20dot%20or%20an%20underscore.%20This%20is%20not%20permitted%20without%20a%20scope.)

**Comment by webpro** [comment]
Thanks for the report @heavybeard! Would you like to send in a pull request?
