### ISSUE TITLE
🐛 Stylelint: "customSyntax" config is not recognised as dependency usage

### ISSUE THREAD

**Issue by duncan-thacker** [webpro-nl/knip#799]
### Prerequisites

- [X] I'm using the latest version
- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://codesandbox.io/p/sandbox/zealous-northcutt-g94nf7

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Description of the issue

Including `"customSyntax": "postcss-less" ` in the stylelint config does not mark `postcss-less` as a used dependency. knip definitely detects the config file correctly, but there is nothing in the plugin code that checks this field. https://github.com/webpro-nl/knip/blob/main/packages/knip/src/plugins/stylelint/index.ts

Knip produces the following report:
```
Unused devDependencies (1)
postcss-less  package.json
```

## Workaround
By switching to a JS config, you can do
```
"customSyntax": require.resolve("postcss-less")
```
which causes the dependency to be correctly marked as used.

**Comment by duncan-thacker** [comment]
I'll try to raise a PR for this at some point, for now it's just a nice-to-have so that knip works better out-of-the-box.

**Comment by webpro** [comment]
Sounds great, thanks in advance! Let me know if you need anything.
