### ISSUE TITLE
🐛 knip command hanging with an empty exported enum key

### ISSUE THREAD

**Issue by ihatem** [webpro-nl/knip#800]
### Prerequisites

- [X] I'm using the latest version
- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://codesandbox.io/p/sandbox/gracious-oskar-2kxcsc

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Description of the issue

I found a very weird bug where knip get stuck at `Analyzing source files...` when there's an exported enum with an empty key: 

```ts 
export enum TestEnum {
  "" = "test",
}
``` 

Note that you can reproduce this bug only when the enum is exported and the key is empty. If you remove the `export` or you replace the empty key by something else it will work.

**Comment by webpro** [comment]
Dang, this is a tough one. Thanks for the report! I'm on it.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.32.0. See [Release 5.32.0](https://github.com/webpro-nl/knip/releases/tag/5.32.0) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._
