### ISSUE TITLE
🔄 incorrectly reports unused devDependency (http-server) used in package.json scripts

### ISSUE THREAD

**Issue by michaelfaith** [webpro-nl/knip#813]
### Prerequisites

- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://codesandbox.io/p/sandbox/knip-http-server-bug-ql6jtc

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Good version

5.33.3

### Bad version

5.34.0

### Description of the regression

After upgrading from 5.33.3 to 5.34.0, we're seeing false positives when`http-server` is only used in a package.json script.
<img width="266" alt="image" src="https://github.com/user-attachments/assets/1953853b-aa48-401b-a057-a252b68a9dc1">

**Comment by webpro** [comment]
Thanks for reporting! You've hit an unfortunate edge case only affecting binaries starting with "http".

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.34.1. See [Release 5.34.1](https://github.com/webpro-nl/knip/releases/tag/5.34.1) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._
