### ISSUE TITLE
🧩 Knip lists the setup files in vite.config as unlisted

### ISSUE THREAD

**Issue by anitajebaraj** [webpro-nl/knip#815]
### Discuss anything related to Knip

how to configure so knip identifies the setup files in vite.config

**Comment by webpro** [comment]
Could you be more specific please?

Please see https://knip.dev/guides/issue-reproduction and put relevant file(s) and I'm more than happy to review and help you out.

**Comment by anitajebaraj** [comment]
I have the vite config with setup files which references other ts/js files. But the setup files  ['libs/common/setupTests.ts', 'libs/common/mocks.js'] are listed by knip as unlisted dependencies. 
{
  test: {
    setupFiles: ['libs/common/setupTests.ts', 'libs/common/mocks.js'],
    coverage: {},
    resolve: {},
  plugins: [],
}

**Comment by webpro** [comment]
Consider making them relative like so:

```
setupFiles: ['./libs/common/setupTests.ts', './libs/common/mocks.js'],
```

**Comment by anitajebaraj** [comment]
Thank you...this works
