### ISSUE TITLE
🐛 knip crashes due to invalid dependency version of picocolors 1.0.0

### ISSUE THREAD

**Issue by chrztoph** [webpro-nl/knip#820]
### Prerequisites

- [X] I'm using the latest version
- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

Sorry no time right now, but if really needed let me know.

### Reproduction access

- [ ] I've made sure the reproduction is publicly accessible

### Description of the issue

Hey,

if a version of `picocolors` lower than `1.1.0` is installed knip crashes with the following:

```
Unlisted dependencies (2)
file:///<redacted>/node_modules/knip/dist/reporters/symbols.js:14
        return [dim(parts[0]), bright(issue.symbol), dim(rest)].join('');
 
TypeError: bright is not a function
```

The problem is that bright colors in picocolors were added with version `1.1.0` (see https://github.com/alexeyraspopov/picocolors/releases/tag/v1.1.0).

This can happen due the dependency version of `picocolors` being set to `^1.0.0` (see https://github.com/webpro-nl/knip/blob/cfcdcbe13cd69a70431c65adddb93f887ba6c367/packages/knip/package.json#L69).

We should bump it to `^1.1.0`.

**Comment by webpro** [comment]
Fixed in #821
