### ISSUE TITLE
💡 Add documentation for how a given plugin works

### ISSUE THREAD

**Issue by thoughtsunificator** [webpro-nl/knip#824]
Looking at the documentation: 

<details>
  <summary>Screenshot</summary>

![knip dev_reference_plugins_eslint](https://github.com/user-attachments/assets/2addc559-30ed-48cd-a587-d8f9dbd22f0b)

</details>

We can see that it does not say anything about what this plugin does.

I would suggest that Knip tries:

- To explain what plugins do or link to https://knip.dev/explanations/plugins#what-does-a-plugin-do
- List related ongoing issues
- Linkify `config` and `entry` options.

This holds true for any plugin listed at https://knip.dev/reference/plugins.

**Comment by webpro** [comment]
Thanks for the suggestions. Let's go over each of them:

> To explain what a certain plugin does

What information would you be looking for? Each plugin links to https://knip.dev/explanations/plugins, this is what all plugins do. Explaining what each plugin individually does would take up too much time, but we could link to implementation/source code to see exactly what it does currently.

> List related ongoing issues

Currently I'm not tagging issues in GitHub to link to particular plugins.

> Linkify `config` and `entry` options.

What do you mean by this?

**Comment by webpro** [comment]
Somehow I feel this conversation isn't gonna be fruitful.
