### ISSUE TITLE
🐛 False positive for Unused exports  if they are referenced in an unused file

### ISSUE THREAD

**Issue by kachkaev** [webpro-nl/knip#826]
### Prerequisites

- [X] I'm using the latest version
- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://codesandbox.io/p/devbox/zealous-goodall-7cy572-forked-pggfq8

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Description of the issue

This might be intended behavior but my initial reaction was that it was a bug. Imagine we have

```ts
// helpers.ts
export const foo = 42;
export const bar = -42;


// unused-file.ts
import { foo } from "./helpers";

console.log(foo);


// index.ts
import { bar } from "./helpers";

console.log(bar);
```

Our `index.ts` file is an entry point, `unused-file.ts` is unused and `helpers.ts` exports two variables, both of which are used. When we run `pnpm run knip` (5.36.0), we get this:

```
Unused files (1)
unused-file.ts

Unused exports (1)
foo  unknown  helpers.ts:1:14
```

Seeing `unused-file.ts` was clearly helpful, but seeing `foo` too confused me. I clicked on `helpers.ts:1:14`, pressed F12 and got this:
![Screenshot 2024-11-01 at 14 45 22](https://github.com/user-attachments/assets/aa153167-7de6-4ccc-ad8a-467ee8e39a38)

_— So `foo` is clearly used, why is it reported?_

In this isolated example it is quite easy to understand the cause. But in a real scenario, when there are quite a few unused files and exports, reported `const foo` feels like a bug. My expectation was that `Unused exports` whould mean ‘not showing anything when pressing F12’ rather than ‘not part of a import graph that includes entry points’. Happy to live with this, just sharing a discovery.

Thanks again for such a great tool! 👏

**Comment by kachkaev** [comment]
Yeah the output looks correct for `npm run knip --fix`– it would remove both `foo` and `unused-file.ts` in one pass.

I wonder if there is any space for some additional indication to avoid dev confusion. Random idea: show `foo` in a section called `Imported only in unused files` (perhaps, with a better title 😅).

**Comment by webpro** [comment]
- Knip: find unused files & exports
- F12: find references to something

They're different things with different goals. This does not indicate a bug nor a false positive. Imho it's actually a strength of Knip: [synergy](https://knip.dev/explanations/why-use-knip#comprehensive) between issue types for better coverage overall.

Unfortunately the dependency and module graph isn't exposed yet, and also with a preprocessor there isn't much you could do here, I'm afraid.

They're issues that should be fixed? Or handled using configuration or JSDoc tags, etc.

**Comment by kachkaev** [comment]
> They're issues that should be fixed?

They are, by removing unused files first, then removing exported consts which are only used in those files. The reason why I’ve opened this issue is a slight confusion that I have faced as a developer when manually going through Knip’s output.

I totally understand your points. If it’s hard to add a new output category (e.g. `Imported only in unused files` next to `Unused exports`), we can keep things as they are. If anyone faces the same confusion, please shout out. I still believe that there is some potential here to tweak what Knip shows, without changing what Knip does. Cheers! 🙌

**Comment by webpro** [comment]
Appreciate the feedback and taking it seriously.

Currently the unused files aren't even read/parsed (i.e. exports and imports aren't extracted). But all sorts of feedback is welcome indeed, especially if something is confusing.
