### ISSUE TITLE
🐛 Code snippets in docs site aren't readable in light mode

### ISSUE THREAD

**Issue by tbroyer** [webpro-nl/knip#846]
### Prerequisites

- [X] I'm using the latest version
- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://knip.dev/overview/getting-started#manual

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Description of the issue

Code snippets in the documentation aren't readable in light mode, with `#F8F8F8` test on white background. I suspect the background is expected to be black rather than white (given how commands, and the filename of snippets, are on black background)

![screenshot showing the issue](https://github.com/user-attachments/assets/8833ade2-fb63-42aa-8c7c-f6a8628f657e)

**Comment by webpro** [comment]
Thanks for the report! Should be fixed now.

I've also added a "documentation" issue type for anything else that might come up (https://github.com/webpro-nl/knip/issues/new/choose)
