### ISSUE TITLE
🐛 Jest plugin should allow ts-node dependecy when using Typescript config

### ISSUE THREAD

**Issue by bigpopakap** [webpro-nl/knip#854]
### Prerequisites

- [X] I'm using the latest version
- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://stackblitz.com/edit/github-rwe1kn?file=README.md

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Description of the issue

# How the repro was set up

1. `npm install -D jest`, install Jest
1. `npm init jest@latest`, and selecting Typescript to use `.ts` for the config (creating `jest.config.ts`)
1. Added `test` script in `package.json` to run Jest tests
1. Added one example test `example.test.js`, so `npm run test` works
1. Then installed `ts-node` (keep reading)

# The issue with Jest

Jest requires `ts-node` to run tests when using the Typescript config file `jest.config.ts`.

If you don't, you'll get the following error in the console
```bash
~/projects/rlmibmmqya.github
❯ npm run test

> @knip/templates-basic@1.0.0 test
> jest

Error: Jest: Failed to parse the TypeScript config file /home/projects/rlmibmmqya.github/jest.config.ts
  Error: Jest: 'ts-node' is required for the TypeScript configuration files. Make sure it is installed
```

# The issue with Knip

Now if you install `ts-node` with `npm install -D ts-node`, tests will run and pass

```bash
~/projects/rlmibmmqya.github 7s
❯ npm run test

> @knip/templates-basic@1.0.0 test
> jest

 PASS  ./example.test.js
  ✓ should run this test (1 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.219 s
```

**However**, running Knip will now flag `ts-node` as an unused dependency

```bash
~/projects/rlmibmmqya.github 2s
❯ npm run knip

> @knip/templates-basic@1.0.0 knip
> knip

Unused devDependencies (1)
ts-node  package.json
```

# Proposed solution

Knip's Jest plugin should detect what _kind_ of Jest config is used. If it's Typescript, it should allowlist the `ts-node` dependency.

**Comment by webpro** [comment]
> Knip's Jest plugin should detect what _kind_ of Jest config is used. If it's Typescript, it should allowlist the ts-node dependency.

If Knip would do that, then `ts-jest` users might be unpleasantly surprised, no?

Could there be another way to detect ts-node is required maybe?

Alternatives:

- Use `ts-jest`
- Add `ts-node` to `ignoreDependencies: []`

**Comment by webpro** [comment]
Typically, cases where this type of magic happens I'm inclined to advice and add it to `ignoreDependencies`. One could argue it's an (optional) peer dependency.

What if if you're running it with something like `tsx jest` or `node --experimental-strip-types jest` or with Bun? Then some of the logic might fall apart and/or become more complex.

Another thing to consider is that Knip also looks for unlisted dependencies, which doesn't go great with the idea of "allowlist".
