### ISSUE TITLE
🔄 Jest configured setup scripts reporting as unused exports when --include-entry-exports is enabled

### ISSUE THREAD

**Issue by stfstoris** [webpro-nl/knip#857]
### Prerequisites

- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://github.com/stfstoris/knip-jest-setup-issue

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Good version

5.33.3

### Bad version

5.34.0

### Description of the regression

Reproduction of issue: https://github.com/stfstoris/knip-jest-setup-issue

There seems to be a regression of an issue my colleague @shawnmcknight logged a while back:  https://github.com/webpro-nl/knip/issues/716, where after we updated `knip` to latest we are now getting unused export errors from our `jest` setup and teardown files with `--include-entry-exports` enabled:

![image](https://github.com/user-attachments/assets/62d1c40a-7d63-4ff2-946e-be2a295c0f43)

Running this on any version **after** original fix version (`5.24.2`) and **before** version `5.34.0` does not give us this error, so it appears that this version introduced regression:

![image](https://github.com/user-attachments/assets/11820d39-928c-4003-b034-3065a70fe507)

**Comment by webpro** [comment]
Thanks the report, @stfstoris! Did a major refactoring around that version and I've missed something indeed. Should be sorted in the next.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.38.1. See [Release 5.38.1](https://github.com/webpro-nl/knip/releases/tag/5.38.1) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._

**Comment by stfstoris** [comment]
@webpro thank you for the quick fix!

**Comment by webpro** [comment]
🫡
