### ISSUE TITLE
💡 Those exported modules that are being used within the current file should not be tagged as unused exports.

### ISSUE THREAD

**Issue by vincent890120** [webpro-nl/knip#858]
### Suggest an idea for Knip

In a file, there are two methods being exported, which are export A and export B. Here, A is imported by app.tsx, and B is being referenced by A. In such a scenario, B would also be identified as an unused export. Can we possibly optimize for such situations? In other words, if the exported module is being referenced within the current file, then it should not be tagged as an unused export.
For example
test.tsx
![image](https://github.com/user-attachments/assets/1072eecd-6f67-43ce-9991-cd2440072f6c)
App.tsx
![image](https://github.com/user-attachments/assets/2a968344-1365-4acc-a1b2-6e5ab63a878a)
B is recognized as an unused module.
![image](https://github.com/user-attachments/assets/262241ee-adc9-43b2-9414-798d0f59381f)

**Comment by webpro** [comment]
While I think Knip is behaving as expected and tries to optimize what's flagged or not, it does provide this option: https://knip.dev/reference/configuration#ignoreexportsusedinfile. Would that work for you

**Comment by vincent890120** [comment]
I really appreciate it, this is quite helpful for me.

**Comment by webpro** [comment]
Excellent, let's close this ticket then.
