### ISSUE TITLE
💡 (ESLint plugin): Support `eslint.config.ts`

### ISSUE THREAD

**Issue by taro-28** [webpro-nl/knip#859]
### Suggest an idea for Knip

Hello!

[ESLint now supports using TypeScript configuration files](https://eslint.org/docs/latest/use/configure/configuration-files#configuration-file) like `eslint.config.ts` as an experimental feature. I’d like to see support for this in the Knip ESLint Plugin as well!

I believe this can be handled simply by updating the `entry` as follows!

https://github.com/webpro-nl/knip/blob/204ce6dd461f5117a6c62047c6b8d9df494f2292/packages/knip/src/plugins/eslint/index.ts#L23

```ts
// Add ts extensions
const entry = ['eslint.config.{js,cjs,mjs,ts,cts,mts}'];
```

Would it be okay if I created a PR for this?

**Comment by webpro** [comment]
I'd love that but there are things holding us back: this is discussed in #818

#806 is also blocked by this

Should add that I didn't check up on the status of things recently.

**Comment by taro-28** [comment]
Got it, I see I missed checking the existing issues…!
I'll close this now and look forward to it being supported someday!
