### ISSUE TITLE
🐛 Default exports are not tracked

### ISSUE THREAD

**Issue by bartekczyz** [webpro-nl/knip#860]
### Prerequisites

- [X] I'm using the latest version
- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://github.com/bartekczyz/knip-default-exports-repro

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Description of the issue

First of all, thank you for this amazing library ⭐ 

This is actually a continuation of https://github.com/webpro-nl/knip/issues/721

I want to find all usages of particular files in my project. It works fine if file exports named objects, but it won't track default exports. 
Sadly, our codebase is huge and I can't refactor so that it uses named exports everywhere.

**Comment by webpro** [comment]
Thanks for the report @bartekczyz! Will release shortly.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.38.3. See [Release 5.38.3](https://github.com/webpro-nl/knip/releases/tag/5.38.3) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._

**Comment by bartekczyz** [comment]
Wow, that was fast! 😱 Thanks @webpro!
