### ISSUE TITLE
🐛 `scp` reports as `Unlisted binaries` in `package.json`

### ISSUE THREAD

**Issue by rakleed** [webpro-nl/knip#862]
### Prerequisites

- [X] I'm using the latest version
- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://stackblitz.com/edit/github-czsnpz?file=package.json

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Description of the issue

`scp` reports as `Unlisted binaries` in `package.json` although it is a [system utility](https://linux.die.net/man/1/scp).

**Comment by webpro** [comment]
```
❯ npx last-publish scp
The last publish date of scp is 5/31/2013
```

More than 10 years ago, let's add it. Would you be willing to submit a PR?

**Comment by rakleed** [comment]
I haven't dived too deep into the code, but would it be enough to add an exception here?

https://github.com/webpro-nl/knip/blob/d551144243896d567aad22b087dd75cb89202e96/packages/knip/fixtures/ignore-dependencies-binaries/knip.ts#L2

https://github.com/webpro-nl/knip/blob/d551144243896d567aad22b087dd75cb89202e96/packages/knip/fixtures/ignore-dependencies-binaries-json/package.json#L14-L19

**Comment by webpro** [comment]
Even better: https://github.com/webpro-nl/knip/blob/main/packages/knip/src/constants.ts#L34-L37
