### ISSUE TITLE
🐛 false positive for package JSONStream

### ISSUE THREAD

**Issue by boneskull** [webpro-nl/knip#869]
### Prerequisites

- [X] I'm using the latest version
- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://codesandbox.io/p/github/boneskull/knip-jsonstream/main?import=true

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Description of the issue

Noticed that `JSONStream` is not picked up correctly by `knip`.

My hunch is that the capitals in the package name are throwing it (or something) off, since you're not supposed to use capitals. 😄

**Comment by webpro** [comment]
Well, that's embarrassing, lol

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.39.1. See [Release 5.39.1](https://github.com/webpro-nl/knip/releases/tag/5.39.1) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._

**Comment by webpro** [comment]
Thanks for the report, @boneskull!
