### ISSUE TITLE
📘 Add package manager commands in command examples to be consistent

### ISSUE THREAD

**Issue by FumiKimura** [webpro-nl/knip#878]
### Link

https://knip.dev/overview/configuration#location

### Description of the issue

Problem: There are different package manager commands in the installation section of `Getting Started`, and the user can switch between the packages managers they are using. In order to be more consistent across documentations, adding this switching is helpful for new users to copy and paste.

Solution: We should make a command example to be able to switch between package managers. This is the example, which I changed in the configuration page of the `Overview`. 

**Before (current, got knip command not found in my terminal)**
<img width="738" alt="image" src="https://github.com/user-attachments/assets/ac5c282c-681d-4f9c-8ddd-7ba2703ac263" />

**After (switch by package manager)**
<img width="744" alt="image" src="https://github.com/user-attachments/assets/43ab44f8-4937-4492-a8d0-90cb6d941f80" />

**Comment by webpro** [comment]
Thanks Norifumi! I like your suggestion, but I think we need to modify it to either one of these:

- `npx knip --config path/to/knip.json`
- `npm run knip -- --config path/to/knip.json`

I'm leaning towards the first one, what do you think?

**Comment by FumiKimura** [comment]
@webpro Thanks for the quick reply. I agree with you that `npx knip --config path/to/knip.json` is better since there is no assumption of npm installation. Can I create PR for this ?

**Comment by webpro** [comment]
That would be swell! Thank you in advance.

**Comment by webpro** [comment]
Actually, I have seconds thoughts on this: all commands might go into `package.json#scripts` and there we don't need any of `npx` etc. Those command examples in the documentation are concise and minimal just to show the essence of that section. So I think no pull request is necessary here :)

**Comment by FumiKimura** [comment]
@webpro Got it thanks. Closing this issue.
